// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

// Hub marks this type as a conversion hub.
func (tr *ReleasePipeline) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReleaseStage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Team) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamLabel) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *TeamWorkflow) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Template) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkflowState) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkspaceLabel) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *WorkspaceSettings) Hub() {}
