// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type DefaultStageInitParameters struct {

	// Color of the stage. **Default** `#f59e0b`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// Name of the stage. **Default** `Started`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type DefaultStageObservation struct {

	// Color of the stage. **Default** `#f59e0b`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// Identifier of the release stage.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the stage. **Default** `Started`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Position of the stage.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type DefaultStageParameters struct {

	// Color of the stage. **Default** `#f59e0b`.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// Name of the stage. **Default** `Started`.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type ReleasePipelineInitParameters struct {
	DefaultStage *DefaultStageInitParameters `json:"defaultStage,omitempty" tf:"default_stage,omitempty"`

	// Glob patterns to filter commits by file path.
	IncludePathPatterns []*string `json:"includePathPatterns,omitempty" tf:"include_path_patterns,omitempty"`

	// Whether this pipeline targets a production environment.
	IsProduction *bool `json:"isProduction,omitempty" tf:"is_production,omitempty"`

	// Name of the release pipeline.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifiers of the teams associated with this pipeline.
	// +listType=set
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`

	// Type of the pipeline: `continuous` or `scheduled`. **Default** `continuous`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReleasePipelineObservation struct {
	DefaultStage *DefaultStageObservation `json:"defaultStage,omitempty" tf:"default_stage,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Glob patterns to filter commits by file path.
	IncludePathPatterns []*string `json:"includePathPatterns,omitempty" tf:"include_path_patterns,omitempty"`

	// Whether this pipeline targets a production environment.
	IsProduction *bool `json:"isProduction,omitempty" tf:"is_production,omitempty"`

	// Name of the release pipeline.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifiers of the teams associated with this pipeline.
	// +listType=set
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`

	// Type of the pipeline: `continuous` or `scheduled`. **Default** `continuous`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReleasePipelineParameters struct {

	// +kubebuilder:validation:Optional
	DefaultStage *DefaultStageParameters `json:"defaultStage,omitempty" tf:"default_stage,omitempty"`

	// Glob patterns to filter commits by file path.
	// +kubebuilder:validation:Optional
	IncludePathPatterns []*string `json:"includePathPatterns,omitempty" tf:"include_path_patterns,omitempty"`

	// Whether this pipeline targets a production environment.
	// +kubebuilder:validation:Optional
	IsProduction *bool `json:"isProduction,omitempty" tf:"is_production,omitempty"`

	// Name of the release pipeline.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifiers of the teams associated with this pipeline.
	// +kubebuilder:validation:Optional
	// +listType=set
	Teams []*string `json:"teams,omitempty" tf:"teams,omitempty"`

	// Type of the pipeline: `continuous` or `scheduled`. **Default** `continuous`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ReleasePipelineSpec defines the desired state of ReleasePipeline
type ReleasePipelineSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ReleasePipelineParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReleasePipelineInitParameters `json:"initProvider,omitempty"`
}

// ReleasePipelineStatus defines the observed state of ReleasePipeline.
type ReleasePipelineStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ReleasePipelineObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ReleasePipeline is the Schema for the ReleasePipelines API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,linear}
type ReleasePipeline struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   ReleasePipelineSpec   `json:"spec"`
	Status ReleasePipelineStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReleasePipelineList contains a list of ReleasePipelines
type ReleasePipelineList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReleasePipeline `json:"items"`
}

// Repository type metadata.
var (
	ReleasePipeline_Kind             = "ReleasePipeline"
	ReleasePipeline_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ReleasePipeline_Kind}.String()
	ReleasePipeline_KindAPIVersion   = ReleasePipeline_Kind + "." + CRDGroupVersion.String()
	ReleasePipeline_GroupVersionKind = CRDGroupVersion.WithKind(ReleasePipeline_Kind)
)

func init() {
	SchemeBuilder.Register(&ReleasePipeline{}, &ReleasePipelineList{})
}
