// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ReleaseStageInitParameters struct {

	// Color of the stage as a HEX string.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// Whether the stage is frozen (only for started type).
	Frozen *bool `json:"frozen,omitempty" tf:"frozen,omitempty"`

	// Name of the release stage.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the release pipeline.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.ReleasePipeline
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	PipelineID *string `json:"pipelineId,omitempty" tf:"pipeline_id,omitempty"`

	// Reference to a ReleasePipeline in linear to populate pipelineId.
	// +kubebuilder:validation:Optional
	PipelineIDRef *v1.Reference `json:"pipelineIdRef,omitempty" tf:"-"`

	// Selector for a ReleasePipeline in linear to populate pipelineId.
	// +kubebuilder:validation:Optional
	PipelineIDSelector *v1.Selector `json:"pipelineIdSelector,omitempty" tf:"-"`

	// Position of the stage within the pipeline.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// Type of the stage: `planned`, `started`, `completed`, or `canceled`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReleaseStageObservation struct {

	// Color of the stage as a HEX string.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// Whether the stage is frozen (only for started type).
	Frozen *bool `json:"frozen,omitempty" tf:"frozen,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name of the release stage.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the release pipeline.
	PipelineID *string `json:"pipelineId,omitempty" tf:"pipeline_id,omitempty"`

	// Position of the stage within the pipeline.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// Type of the stage: `planned`, `started`, `completed`, or `canceled`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ReleaseStageParameters struct {

	// Color of the stage as a HEX string.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// Whether the stage is frozen (only for started type).
	// +kubebuilder:validation:Optional
	Frozen *bool `json:"frozen,omitempty" tf:"frozen,omitempty"`

	// Name of the release stage.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Identifier of the release pipeline.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.ReleasePipeline
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	PipelineID *string `json:"pipelineId,omitempty" tf:"pipeline_id,omitempty"`

	// Reference to a ReleasePipeline in linear to populate pipelineId.
	// +kubebuilder:validation:Optional
	PipelineIDRef *v1.Reference `json:"pipelineIdRef,omitempty" tf:"-"`

	// Selector for a ReleasePipeline in linear to populate pipelineId.
	// +kubebuilder:validation:Optional
	PipelineIDSelector *v1.Selector `json:"pipelineIdSelector,omitempty" tf:"-"`

	// Position of the stage within the pipeline.
	// +kubebuilder:validation:Optional
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// Type of the stage: `planned`, `started`, `completed`, or `canceled`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// ReleaseStageSpec defines the desired state of ReleaseStage
type ReleaseStageSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ReleaseStageParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReleaseStageInitParameters `json:"initProvider,omitempty"`
}

// ReleaseStageStatus defines the observed state of ReleaseStage.
type ReleaseStageStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ReleaseStageObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ReleaseStage is the Schema for the ReleaseStages API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,linear}
type ReleaseStage struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.color) || (has(self.initProvider) && has(self.initProvider.color))",message="spec.forProvider.color is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.position) || (has(self.initProvider) && has(self.initProvider.position))",message="spec.forProvider.position is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   ReleaseStageSpec   `json:"spec"`
	Status ReleaseStageStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReleaseStageList contains a list of ReleaseStages
type ReleaseStageList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReleaseStage `json:"items"`
}

// Repository type metadata.
var (
	ReleaseStage_Kind             = "ReleaseStage"
	ReleaseStage_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ReleaseStage_Kind}.String()
	ReleaseStage_KindAPIVersion   = ReleaseStage_Kind + "." + CRDGroupVersion.String()
	ReleaseStage_GroupVersionKind = CRDGroupVersion.WithKind(ReleaseStage_Kind)
)

func init() {
	SchemeBuilder.Register(&ReleaseStage{}, &ReleaseStageList{})
}
