// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TeamMembershipInitParameters struct {

	// Whether the user is a team owner.
	Owner *bool `json:"owner,omitempty" tf:"owner,omitempty"`

	// Identifier of the team.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.Team
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v1.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v1.Selector `json:"teamIdSelector,omitempty" tf:"-"`

	// Identifier of the user.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TeamMembershipObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether the user is a team owner.
	Owner *bool `json:"owner,omitempty" tf:"owner,omitempty"`

	// Identifier of the team.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Identifier of the user.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type TeamMembershipParameters struct {

	// Whether the user is a team owner.
	// +kubebuilder:validation:Optional
	Owner *bool `json:"owner,omitempty" tf:"owner,omitempty"`

	// Identifier of the team.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.Team
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v1.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v1.Selector `json:"teamIdSelector,omitempty" tf:"-"`

	// Identifier of the user.
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

// TeamMembershipSpec defines the desired state of TeamMembership
type TeamMembershipSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TeamMembershipParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamMembershipInitParameters `json:"initProvider,omitempty"`
}

// TeamMembershipStatus defines the observed state of TeamMembership.
type TeamMembershipStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamMembershipObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TeamMembership is the Schema for the TeamMemberships API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,linear}
type TeamMembership struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.userId) || (has(self.initProvider) && has(self.initProvider.userId))",message="spec.forProvider.userId is a required parameter"
	Spec   TeamMembershipSpec   `json:"spec"`
	Status TeamMembershipStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamMembershipList contains a list of TeamMemberships
type TeamMembershipList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TeamMembership `json:"items"`
}

// Repository type metadata.
var (
	TeamMembership_Kind             = "TeamMembership"
	TeamMembership_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TeamMembership_Kind}.String()
	TeamMembership_KindAPIVersion   = TeamMembership_Kind + "." + CRDGroupVersion.String()
	TeamMembership_GroupVersionKind = CRDGroupVersion.WithKind(TeamMembership_Kind)
)

func init() {
	SchemeBuilder.Register(&TeamMembership{}, &TeamMembershipList{})
}
