// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TeamLabelInitParameters struct {

	// (String) Color of the label.
	// Color of the label.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the label.
	// Description of the label.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the label is a group (parent) label.
	// Whether the label is a group (parent) label.
	IsGroup *bool `json:"isGroup,omitempty" tf:"is_group,omitempty"`

	// (String) Parent (label group) of the label.
	// Parent (label group) of the label.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the team.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.Team
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v1.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v1.Selector `json:"teamIdSelector,omitempty" tf:"-"`
}

type TeamLabelObservation struct {

	// (String) Color of the label.
	// Color of the label.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the label.
	// Description of the label.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the label.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Whether the label is a group (parent) label.
	// Whether the label is a group (parent) label.
	IsGroup *bool `json:"isGroup,omitempty" tf:"is_group,omitempty"`

	// (String) Parent (label group) of the label.
	// Parent (label group) of the label.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the team.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`
}

type TeamLabelParameters struct {

	// (String) Color of the label.
	// Color of the label.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the label.
	// Description of the label.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the label is a group (parent) label.
	// Whether the label is a group (parent) label.
	// +kubebuilder:validation:Optional
	IsGroup *bool `json:"isGroup,omitempty" tf:"is_group,omitempty"`

	// (String) Parent (label group) of the label.
	// Parent (label group) of the label.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the team.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.Team
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v1.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v1.Selector `json:"teamIdSelector,omitempty" tf:"-"`
}

// TeamLabelSpec defines the desired state of TeamLabel
type TeamLabelSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TeamLabelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamLabelInitParameters `json:"initProvider,omitempty"`
}

// TeamLabelStatus defines the observed state of TeamLabel.
type TeamLabelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamLabelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TeamLabel is the Schema for the TeamLabels API. Linear team label.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,linear}
type TeamLabel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TeamLabelSpec   `json:"spec"`
	Status            TeamLabelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamLabelList contains a list of TeamLabels
type TeamLabelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TeamLabel `json:"items"`
}

// Repository type metadata.
var (
	TeamLabel_Kind             = "TeamLabel"
	TeamLabel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TeamLabel_Kind}.String()
	TeamLabel_KindAPIVersion   = TeamLabel_Kind + "." + CRDGroupVersion.String()
	TeamLabel_GroupVersionKind = CRDGroupVersion.WithKind(TeamLabel_Kind)
)

func init() {
	SchemeBuilder.Register(&TeamLabel{}, &TeamLabelList{})
}
