// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BacklogWorkflowStateInitParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#bec2c8`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Backlog`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type BacklogWorkflowStateObservation struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#bec2c8`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the workflow state.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Backlog`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Position of the workflow state.
	// Position of the workflow state.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type BacklogWorkflowStateParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#bec2c8`.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Backlog`.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CanceledWorkflowStateInitParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#95a2b3`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Canceled`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CanceledWorkflowStateObservation struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#95a2b3`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the workflow state.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Canceled`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Position of the workflow state.
	// Position of the workflow state.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type CanceledWorkflowStateParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#95a2b3`.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Canceled`.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CompletedWorkflowStateInitParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#5e6ad2`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Done`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CompletedWorkflowStateObservation struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#5e6ad2`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the workflow state.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Done`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Position of the workflow state.
	// Position of the workflow state.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type CompletedWorkflowStateParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#5e6ad2`.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Done`.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type CyclesInitParameters struct {

	// (Boolean) Auto add completed issues that don't belong to any cycle to the active cycle. Default true.
	// Auto add completed issues that don't belong to any cycle to the active cycle. **Default** `true`.
	AutoAddCompleted *bool `json:"autoAddCompleted,omitempty" tf:"auto_add_completed,omitempty"`

	// (Boolean) Auto add started issues that don't belong to any cycle to the active cycle. Default true.
	// Auto add started issues that don't belong to any cycle to the active cycle. **Default** `true`.
	AutoAddStarted *bool `json:"autoAddStarted,omitempty" tf:"auto_add_started,omitempty"`

	// (Number) Cooldown time between cycles in weeks. Default 0.
	// Cooldown time between cycles in weeks. **Default** `0`.
	Cooldown *float64 `json:"cooldown,omitempty" tf:"cooldown,omitempty"`

	// (Number) Duration of the cycle in weeks. Default 1.
	// Duration of the cycle in weeks. **Default** `1`.
	Duration *float64 `json:"duration,omitempty" tf:"duration,omitempty"`

	// (Boolean) Enable cycles for the team. Default false.
	// Enable cycles for the team. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether all active issues need to have a cycle. Default false.
	// Whether all active issues need to have a cycle. **Default** `false`.
	NeedForActive *bool `json:"needForActive,omitempty" tf:"need_for_active,omitempty"`

	// (Number) Start day of the cycle. Sunday is 0, Saturday is 6. Default 0.
	// Start day of the cycle. Sunday is 0, Saturday is 6. **Default** `0`.
	StartDay *float64 `json:"startDay,omitempty" tf:"start_day,omitempty"`

	// (Number) Number of upcoming cycles to automatically create. Default 2.
	// Number of upcoming cycles to automatically create. **Default** `2`.
	Upcoming *float64 `json:"upcoming,omitempty" tf:"upcoming,omitempty"`
}

type CyclesObservation struct {

	// (Boolean) Auto add completed issues that don't belong to any cycle to the active cycle. Default true.
	// Auto add completed issues that don't belong to any cycle to the active cycle. **Default** `true`.
	AutoAddCompleted *bool `json:"autoAddCompleted,omitempty" tf:"auto_add_completed,omitempty"`

	// (Boolean) Auto add started issues that don't belong to any cycle to the active cycle. Default true.
	// Auto add started issues that don't belong to any cycle to the active cycle. **Default** `true`.
	AutoAddStarted *bool `json:"autoAddStarted,omitempty" tf:"auto_add_started,omitempty"`

	// (Number) Cooldown time between cycles in weeks. Default 0.
	// Cooldown time between cycles in weeks. **Default** `0`.
	Cooldown *float64 `json:"cooldown,omitempty" tf:"cooldown,omitempty"`

	// (Number) Duration of the cycle in weeks. Default 1.
	// Duration of the cycle in weeks. **Default** `1`.
	Duration *float64 `json:"duration,omitempty" tf:"duration,omitempty"`

	// (Boolean) Enable cycles for the team. Default false.
	// Enable cycles for the team. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether all active issues need to have a cycle. Default false.
	// Whether all active issues need to have a cycle. **Default** `false`.
	NeedForActive *bool `json:"needForActive,omitempty" tf:"need_for_active,omitempty"`

	// (Number) Start day of the cycle. Sunday is 0, Saturday is 6. Default 0.
	// Start day of the cycle. Sunday is 0, Saturday is 6. **Default** `0`.
	StartDay *float64 `json:"startDay,omitempty" tf:"start_day,omitempty"`

	// (Number) Number of upcoming cycles to automatically create. Default 2.
	// Number of upcoming cycles to automatically create. **Default** `2`.
	Upcoming *float64 `json:"upcoming,omitempty" tf:"upcoming,omitempty"`
}

type CyclesParameters struct {

	// (Boolean) Auto add completed issues that don't belong to any cycle to the active cycle. Default true.
	// Auto add completed issues that don't belong to any cycle to the active cycle. **Default** `true`.
	// +kubebuilder:validation:Optional
	AutoAddCompleted *bool `json:"autoAddCompleted,omitempty" tf:"auto_add_completed,omitempty"`

	// (Boolean) Auto add started issues that don't belong to any cycle to the active cycle. Default true.
	// Auto add started issues that don't belong to any cycle to the active cycle. **Default** `true`.
	// +kubebuilder:validation:Optional
	AutoAddStarted *bool `json:"autoAddStarted,omitempty" tf:"auto_add_started,omitempty"`

	// (Number) Cooldown time between cycles in weeks. Default 0.
	// Cooldown time between cycles in weeks. **Default** `0`.
	// +kubebuilder:validation:Optional
	Cooldown *float64 `json:"cooldown,omitempty" tf:"cooldown,omitempty"`

	// (Number) Duration of the cycle in weeks. Default 1.
	// Duration of the cycle in weeks. **Default** `1`.
	// +kubebuilder:validation:Optional
	Duration *float64 `json:"duration,omitempty" tf:"duration,omitempty"`

	// (Boolean) Enable cycles for the team. Default false.
	// Enable cycles for the team. **Default** `false`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether all active issues need to have a cycle. Default false.
	// Whether all active issues need to have a cycle. **Default** `false`.
	// +kubebuilder:validation:Optional
	NeedForActive *bool `json:"needForActive,omitempty" tf:"need_for_active,omitempty"`

	// (Number) Start day of the cycle. Sunday is 0, Saturday is 6. Default 0.
	// Start day of the cycle. Sunday is 0, Saturday is 6. **Default** `0`.
	// +kubebuilder:validation:Optional
	StartDay *float64 `json:"startDay,omitempty" tf:"start_day,omitempty"`

	// (Number) Number of upcoming cycles to automatically create. Default 2.
	// Number of upcoming cycles to automatically create. **Default** `2`.
	// +kubebuilder:validation:Optional
	Upcoming *float64 `json:"upcoming,omitempty" tf:"upcoming,omitempty"`
}

type EstimationInitParameters struct {

	// (Boolean) Whether zero is allowed as an estimation. Default false.
	// Whether zero is allowed as an estimation. **Default** `false`.
	AllowZero *bool `json:"allowZero,omitempty" tf:"allow_zero,omitempty"`

	// (Number) Default estimation for issues that are unestimated. Default 1.
	// Default estimation for issues that are unestimated. **Default** `1`.
	Default *float64 `json:"default,omitempty" tf:"default,omitempty"`

	// (Boolean) Whether the team uses extended estimation. Default false.
	// Whether the team uses extended estimation. **Default** `false`.
	Extended *bool `json:"extended,omitempty" tf:"extended,omitempty"`

	// (String) Issue estimation type for the team. Default notUsed.
	// Issue estimation type for the team. **Default** `notUsed`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EstimationObservation struct {

	// (Boolean) Whether zero is allowed as an estimation. Default false.
	// Whether zero is allowed as an estimation. **Default** `false`.
	AllowZero *bool `json:"allowZero,omitempty" tf:"allow_zero,omitempty"`

	// (Number) Default estimation for issues that are unestimated. Default 1.
	// Default estimation for issues that are unestimated. **Default** `1`.
	Default *float64 `json:"default,omitempty" tf:"default,omitempty"`

	// (Boolean) Whether the team uses extended estimation. Default false.
	// Whether the team uses extended estimation. **Default** `false`.
	Extended *bool `json:"extended,omitempty" tf:"extended,omitempty"`

	// (String) Issue estimation type for the team. Default notUsed.
	// Issue estimation type for the team. **Default** `notUsed`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type EstimationParameters struct {

	// (Boolean) Whether zero is allowed as an estimation. Default false.
	// Whether zero is allowed as an estimation. **Default** `false`.
	// +kubebuilder:validation:Optional
	AllowZero *bool `json:"allowZero,omitempty" tf:"allow_zero,omitempty"`

	// (Number) Default estimation for issues that are unestimated. Default 1.
	// Default estimation for issues that are unestimated. **Default** `1`.
	// +kubebuilder:validation:Optional
	Default *float64 `json:"default,omitempty" tf:"default,omitempty"`

	// (Boolean) Whether the team uses extended estimation. Default false.
	// Whether the team uses extended estimation. **Default** `false`.
	// +kubebuilder:validation:Optional
	Extended *bool `json:"extended,omitempty" tf:"extended,omitempty"`

	// (String) Issue estimation type for the team. Default notUsed.
	// Issue estimation type for the team. **Default** `notUsed`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type StartedWorkflowStateInitParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#f2c94c`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `In Progress`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type StartedWorkflowStateObservation struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#f2c94c`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the workflow state.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `In Progress`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Position of the workflow state.
	// Position of the workflow state.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type StartedWorkflowStateParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#f2c94c`.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `In Progress`.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type TeamInitParameters struct {

	// (Boolean) Allow members to manage labels in the team.
	// Allow members to manage labels in the team.
	AllowMembersToManageLabels *bool `json:"allowMembersToManageLabels,omitempty" tf:"allow_members_to_manage_labels,omitempty"`

	// (Boolean) Allow members to manage members of the team.
	// Allow members to manage members of the team.
	AllowMembersToManageMembers *bool `json:"allowMembersToManageMembers,omitempty" tf:"allow_members_to_manage_members,omitempty"`

	// (Boolean) Allow members to manage the team.
	// Allow members to manage the team.
	AllowMembersToManageTeam *bool `json:"allowMembersToManageTeam,omitempty" tf:"allow_members_to_manage_team,omitempty"`

	// (Boolean) Allow members to manage templates in the team.
	// Allow members to manage templates in the team.
	AllowMembersToManageTemplates *bool `json:"allowMembersToManageTemplates,omitempty" tf:"allow_members_to_manage_templates,omitempty"`

	// (Number) Period after which closed and completed issues are automatically archived, in months. Default 6.
	// Period after which closed and completed issues are automatically archived, in months. **Default** `6`.
	AutoArchivePeriod *float64 `json:"autoArchivePeriod,omitempty" tf:"auto_archive_period,omitempty"`

	// (Boolean) Whether to automatically close child issues when their parent issue is closed. Default false.
	// Whether to automatically close child issues when their parent issue is closed. **Default** `false`.
	AutoCloseChildIssues *bool `json:"autoCloseChildIssues,omitempty" tf:"auto_close_child_issues,omitempty"`

	// (Boolean) Whether to automatically close parent issues when all their child issues are closed. Default false.
	// Whether to automatically close parent issues when all their child issues are closed. **Default** `false`.
	AutoCloseParentIssues *bool `json:"autoCloseParentIssues,omitempty" tf:"auto_close_parent_issues,omitempty"`

	// completed or non-canceled issues are automatically closed, in months. Default 6. Use
	// Period after which non-completed or non-canceled issues are automatically closed, in months. **Default** `6`. *Use `0` for turning this off.*
	AutoClosePeriod *float64 `json:"autoClosePeriod,omitempty" tf:"auto_close_period,omitempty"`

	// (Attributes) Settings for the backlog workflow state that is created by default for the team. Position is always  (see below for nested schema)
	BacklogWorkflowState *BacklogWorkflowStateInitParameters `json:"backlogWorkflowState,omitempty" tf:"backlog_workflow_state,omitempty"`

	// (Attributes) Settings for the canceled workflow state that is created by default for the team. Position is always  (see below for nested schema)
	CanceledWorkflowState *CanceledWorkflowStateInitParameters `json:"canceledWorkflowState,omitempty" tf:"canceled_workflow_state,omitempty"`

	// (String) Color of the team.
	// Color of the team.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (Attributes) Settings for the completed workflow state that is created by default for the team. Position is always  (see below for nested schema)
	CompletedWorkflowState *CompletedWorkflowStateInitParameters `json:"completedWorkflowState,omitempty" tf:"completed_workflow_state,omitempty"`

	// (Attributes) Cycle settings of the team. (see below for nested schema)
	Cycles *CyclesInitParameters `json:"cycles,omitempty" tf:"cycles,omitempty"`

	// (String) Description of the team.
	// Description of the team.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Enable moving issues to bottom of the column when changing state. Default false.
	// Enable moving issues to bottom of the column when changing state. **Default** `false`.
	EnableIssueDefaultToBottom *bool `json:"enableIssueDefaultToBottom,omitempty" tf:"enable_issue_default_to_bottom,omitempty"`

	// (Boolean) Enable issue history grouping for the team. Default true.
	// Enable issue history grouping for the team. **Default** `true`.
	EnableIssueHistoryGrouping *bool `json:"enableIssueHistoryGrouping,omitempty" tf:"enable_issue_history_grouping,omitempty"`

	// (Boolean) Enable resolved thread AI summaries for the team. Default true.
	// Enable resolved thread AI summaries for the team. **Default** `true`.
	EnableThreadSummaries *bool `json:"enableThreadSummaries,omitempty" tf:"enable_thread_summaries,omitempty"`

	// (Attributes) Issue estimation settings of the team. (see below for nested schema)
	Estimation *EstimationInitParameters `json:"estimation,omitempty" tf:"estimation,omitempty"`

	// (String) Icon of the team.
	// Icon of the team.
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the team.
	// Name of the team.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent team.
	// Identifier of the parent team.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Boolean) Privacy of the team. Default false.
	// Privacy of the team. **Default** `false`.
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (Attributes) Settings for the started workflow state that is created by default for the team. Position is always  (see below for nested schema)
	StartedWorkflowState *StartedWorkflowStateInitParameters `json:"startedWorkflowState,omitempty" tf:"started_workflow_state,omitempty"`

	// (String) Timezone of the team. Default Etc/GMT.
	// Timezone of the team. **Default** `Etc/GMT`.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// (Attributes) Triage settings of the team. (see below for nested schema)
	Triage *TriageInitParameters `json:"triage,omitempty" tf:"triage,omitempty"`

	// (Attributes) Settings for the unstarted workflow state that is created by default for the team. Position is always  (see below for nested schema)
	UnstartedWorkflowState *UnstartedWorkflowStateInitParameters `json:"unstartedWorkflowState,omitempty" tf:"unstarted_workflow_state,omitempty"`
}

type TeamObservation struct {

	// (Boolean) Allow members to manage labels in the team.
	// Allow members to manage labels in the team.
	AllowMembersToManageLabels *bool `json:"allowMembersToManageLabels,omitempty" tf:"allow_members_to_manage_labels,omitempty"`

	// (Boolean) Allow members to manage members of the team.
	// Allow members to manage members of the team.
	AllowMembersToManageMembers *bool `json:"allowMembersToManageMembers,omitempty" tf:"allow_members_to_manage_members,omitempty"`

	// (Boolean) Allow members to manage the team.
	// Allow members to manage the team.
	AllowMembersToManageTeam *bool `json:"allowMembersToManageTeam,omitempty" tf:"allow_members_to_manage_team,omitempty"`

	// (Boolean) Allow members to manage templates in the team.
	// Allow members to manage templates in the team.
	AllowMembersToManageTemplates *bool `json:"allowMembersToManageTemplates,omitempty" tf:"allow_members_to_manage_templates,omitempty"`

	// (Number) Period after which closed and completed issues are automatically archived, in months. Default 6.
	// Period after which closed and completed issues are automatically archived, in months. **Default** `6`.
	AutoArchivePeriod *float64 `json:"autoArchivePeriod,omitempty" tf:"auto_archive_period,omitempty"`

	// (Boolean) Whether to automatically close child issues when their parent issue is closed. Default false.
	// Whether to automatically close child issues when their parent issue is closed. **Default** `false`.
	AutoCloseChildIssues *bool `json:"autoCloseChildIssues,omitempty" tf:"auto_close_child_issues,omitempty"`

	// (Boolean) Whether to automatically close parent issues when all their child issues are closed. Default false.
	// Whether to automatically close parent issues when all their child issues are closed. **Default** `false`.
	AutoCloseParentIssues *bool `json:"autoCloseParentIssues,omitempty" tf:"auto_close_parent_issues,omitempty"`

	// completed or non-canceled issues are automatically closed, in months. Default 6. Use
	// Period after which non-completed or non-canceled issues are automatically closed, in months. **Default** `6`. *Use `0` for turning this off.*
	AutoClosePeriod *float64 `json:"autoClosePeriod,omitempty" tf:"auto_close_period,omitempty"`

	// (Attributes) Settings for the backlog workflow state that is created by default for the team. Position is always  (see below for nested schema)
	BacklogWorkflowState *BacklogWorkflowStateObservation `json:"backlogWorkflowState,omitempty" tf:"backlog_workflow_state,omitempty"`

	// (Attributes) Settings for the canceled workflow state that is created by default for the team. Position is always  (see below for nested schema)
	CanceledWorkflowState *CanceledWorkflowStateObservation `json:"canceledWorkflowState,omitempty" tf:"canceled_workflow_state,omitempty"`

	// (String) Color of the team.
	// Color of the team.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (Attributes) Settings for the completed workflow state that is created by default for the team. Position is always  (see below for nested schema)
	CompletedWorkflowState *CompletedWorkflowStateObservation `json:"completedWorkflowState,omitempty" tf:"completed_workflow_state,omitempty"`

	// (Attributes) Cycle settings of the team. (see below for nested schema)
	Cycles *CyclesObservation `json:"cycles,omitempty" tf:"cycles,omitempty"`

	// (String) Description of the team.
	// Description of the team.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Enable moving issues to bottom of the column when changing state. Default false.
	// Enable moving issues to bottom of the column when changing state. **Default** `false`.
	EnableIssueDefaultToBottom *bool `json:"enableIssueDefaultToBottom,omitempty" tf:"enable_issue_default_to_bottom,omitempty"`

	// (Boolean) Enable issue history grouping for the team. Default true.
	// Enable issue history grouping for the team. **Default** `true`.
	EnableIssueHistoryGrouping *bool `json:"enableIssueHistoryGrouping,omitempty" tf:"enable_issue_history_grouping,omitempty"`

	// (Boolean) Enable resolved thread AI summaries for the team. Default true.
	// Enable resolved thread AI summaries for the team. **Default** `true`.
	EnableThreadSummaries *bool `json:"enableThreadSummaries,omitempty" tf:"enable_thread_summaries,omitempty"`

	// (Attributes) Issue estimation settings of the team. (see below for nested schema)
	Estimation *EstimationObservation `json:"estimation,omitempty" tf:"estimation,omitempty"`

	// (String) Identifier of the team.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Icon of the team.
	// Icon of the team.
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the team.
	// Name of the team.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent team.
	// Identifier of the parent team.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Boolean) Privacy of the team. Default false.
	// Privacy of the team. **Default** `false`.
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (Attributes) Settings for the started workflow state that is created by default for the team. Position is always  (see below for nested schema)
	StartedWorkflowState *StartedWorkflowStateObservation `json:"startedWorkflowState,omitempty" tf:"started_workflow_state,omitempty"`

	// (String) Timezone of the team. Default Etc/GMT.
	// Timezone of the team. **Default** `Etc/GMT`.
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// (Attributes) Triage settings of the team. (see below for nested schema)
	Triage *TriageObservation `json:"triage,omitempty" tf:"triage,omitempty"`

	// (Attributes) Settings for the unstarted workflow state that is created by default for the team. Position is always  (see below for nested schema)
	UnstartedWorkflowState *UnstartedWorkflowStateObservation `json:"unstartedWorkflowState,omitempty" tf:"unstarted_workflow_state,omitempty"`
}

type TeamParameters struct {

	// (Boolean) Allow members to manage labels in the team.
	// Allow members to manage labels in the team.
	// +kubebuilder:validation:Optional
	AllowMembersToManageLabels *bool `json:"allowMembersToManageLabels,omitempty" tf:"allow_members_to_manage_labels,omitempty"`

	// (Boolean) Allow members to manage members of the team.
	// Allow members to manage members of the team.
	// +kubebuilder:validation:Optional
	AllowMembersToManageMembers *bool `json:"allowMembersToManageMembers,omitempty" tf:"allow_members_to_manage_members,omitempty"`

	// (Boolean) Allow members to manage the team.
	// Allow members to manage the team.
	// +kubebuilder:validation:Optional
	AllowMembersToManageTeam *bool `json:"allowMembersToManageTeam,omitempty" tf:"allow_members_to_manage_team,omitempty"`

	// (Boolean) Allow members to manage templates in the team.
	// Allow members to manage templates in the team.
	// +kubebuilder:validation:Optional
	AllowMembersToManageTemplates *bool `json:"allowMembersToManageTemplates,omitempty" tf:"allow_members_to_manage_templates,omitempty"`

	// (Number) Period after which closed and completed issues are automatically archived, in months. Default 6.
	// Period after which closed and completed issues are automatically archived, in months. **Default** `6`.
	// +kubebuilder:validation:Optional
	AutoArchivePeriod *float64 `json:"autoArchivePeriod,omitempty" tf:"auto_archive_period,omitempty"`

	// (Boolean) Whether to automatically close child issues when their parent issue is closed. Default false.
	// Whether to automatically close child issues when their parent issue is closed. **Default** `false`.
	// +kubebuilder:validation:Optional
	AutoCloseChildIssues *bool `json:"autoCloseChildIssues,omitempty" tf:"auto_close_child_issues,omitempty"`

	// (Boolean) Whether to automatically close parent issues when all their child issues are closed. Default false.
	// Whether to automatically close parent issues when all their child issues are closed. **Default** `false`.
	// +kubebuilder:validation:Optional
	AutoCloseParentIssues *bool `json:"autoCloseParentIssues,omitempty" tf:"auto_close_parent_issues,omitempty"`

	// completed or non-canceled issues are automatically closed, in months. Default 6. Use
	// Period after which non-completed or non-canceled issues are automatically closed, in months. **Default** `6`. *Use `0` for turning this off.*
	// +kubebuilder:validation:Optional
	AutoClosePeriod *float64 `json:"autoClosePeriod,omitempty" tf:"auto_close_period,omitempty"`

	// (Attributes) Settings for the backlog workflow state that is created by default for the team. Position is always  (see below for nested schema)
	// +kubebuilder:validation:Optional
	BacklogWorkflowState *BacklogWorkflowStateParameters `json:"backlogWorkflowState,omitempty" tf:"backlog_workflow_state,omitempty"`

	// (Attributes) Settings for the canceled workflow state that is created by default for the team. Position is always  (see below for nested schema)
	// +kubebuilder:validation:Optional
	CanceledWorkflowState *CanceledWorkflowStateParameters `json:"canceledWorkflowState,omitempty" tf:"canceled_workflow_state,omitempty"`

	// (String) Color of the team.
	// Color of the team.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (Attributes) Settings for the completed workflow state that is created by default for the team. Position is always  (see below for nested schema)
	// +kubebuilder:validation:Optional
	CompletedWorkflowState *CompletedWorkflowStateParameters `json:"completedWorkflowState,omitempty" tf:"completed_workflow_state,omitempty"`

	// (Attributes) Cycle settings of the team. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Cycles *CyclesParameters `json:"cycles,omitempty" tf:"cycles,omitempty"`

	// (String) Description of the team.
	// Description of the team.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Enable moving issues to bottom of the column when changing state. Default false.
	// Enable moving issues to bottom of the column when changing state. **Default** `false`.
	// +kubebuilder:validation:Optional
	EnableIssueDefaultToBottom *bool `json:"enableIssueDefaultToBottom,omitempty" tf:"enable_issue_default_to_bottom,omitempty"`

	// (Boolean) Enable issue history grouping for the team. Default true.
	// Enable issue history grouping for the team. **Default** `true`.
	// +kubebuilder:validation:Optional
	EnableIssueHistoryGrouping *bool `json:"enableIssueHistoryGrouping,omitempty" tf:"enable_issue_history_grouping,omitempty"`

	// (Boolean) Enable resolved thread AI summaries for the team. Default true.
	// Enable resolved thread AI summaries for the team. **Default** `true`.
	// +kubebuilder:validation:Optional
	EnableThreadSummaries *bool `json:"enableThreadSummaries,omitempty" tf:"enable_thread_summaries,omitempty"`

	// (Attributes) Issue estimation settings of the team. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Estimation *EstimationParameters `json:"estimation,omitempty" tf:"estimation,omitempty"`

	// (String) Icon of the team.
	// Icon of the team.
	// +kubebuilder:validation:Optional
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the team.
	// Name of the team.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) Identifier of the parent team.
	// Identifier of the parent team.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`

	// (Boolean) Privacy of the team. Default false.
	// Privacy of the team. **Default** `false`.
	// +kubebuilder:validation:Optional
	Private *bool `json:"private,omitempty" tf:"private,omitempty"`

	// (Attributes) Settings for the started workflow state that is created by default for the team. Position is always  (see below for nested schema)
	// +kubebuilder:validation:Optional
	StartedWorkflowState *StartedWorkflowStateParameters `json:"startedWorkflowState,omitempty" tf:"started_workflow_state,omitempty"`

	// (String) Timezone of the team. Default Etc/GMT.
	// Timezone of the team. **Default** `Etc/GMT`.
	// +kubebuilder:validation:Optional
	Timezone *string `json:"timezone,omitempty" tf:"timezone,omitempty"`

	// (Attributes) Triage settings of the team. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Triage *TriageParameters `json:"triage,omitempty" tf:"triage,omitempty"`

	// (Attributes) Settings for the unstarted workflow state that is created by default for the team. Position is always  (see below for nested schema)
	// +kubebuilder:validation:Optional
	UnstartedWorkflowState *UnstartedWorkflowStateParameters `json:"unstartedWorkflowState,omitempty" tf:"unstarted_workflow_state,omitempty"`
}

type TriageInitParameters struct {

	// (Boolean) Enable cycles for the team. Default false.
	// Enable triage mode for the team. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether an issue needs to have a priority set before leaving triage. Default false.
	// Whether an issue needs to have a priority set before leaving triage. **Default** `false`.
	RequirePriority *bool `json:"requirePriority,omitempty" tf:"require_priority,omitempty"`
}

type TriageObservation struct {

	// (Boolean) Enable cycles for the team. Default false.
	// Enable triage mode for the team. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether an issue needs to have a priority set before leaving triage. Default false.
	// Whether an issue needs to have a priority set before leaving triage. **Default** `false`.
	RequirePriority *bool `json:"requirePriority,omitempty" tf:"require_priority,omitempty"`
}

type TriageParameters struct {

	// (Boolean) Enable cycles for the team. Default false.
	// Enable triage mode for the team. **Default** `false`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (Boolean) Whether an issue needs to have a priority set before leaving triage. Default false.
	// Whether an issue needs to have a priority set before leaving triage. **Default** `false`.
	// +kubebuilder:validation:Optional
	RequirePriority *bool `json:"requirePriority,omitempty" tf:"require_priority,omitempty"`
}

type UnstartedWorkflowStateInitParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#e2e2e2`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Todo`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type UnstartedWorkflowStateObservation struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#e2e2e2`.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the workflow state.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Todo`.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (Number) Position of the workflow state.
	// Position of the workflow state.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`
}

type UnstartedWorkflowStateParameters struct {

	// (String) Color of the team.
	// Color of the workflow state. **Default** `#e2e2e2`.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the team.
	// Description of the workflow state.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Name of the team.
	// Name of the workflow state. **Default** `Todo`.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// TeamSpec defines the desired state of Team
type TeamSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TeamParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamInitParameters `json:"initProvider,omitempty"`
}

// TeamStatus defines the observed state of Team.
type TeamStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Team is the Schema for the Teams API. Linear team.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,linear}
type Team struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TeamSpec   `json:"spec"`
	Status TeamStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamList contains a list of Teams
type TeamList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Team `json:"items"`
}

// Repository type metadata.
var (
	Team_Kind             = "Team"
	Team_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Team_Kind}.String()
	Team_KindAPIVersion   = Team_Kind + "." + CRDGroupVersion.String()
	Team_GroupVersionKind = CRDGroupVersion.WithKind(Team_Kind)
)

func init() {
	SchemeBuilder.Register(&Team{}, &TeamList{})
}
