// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type TemplateInitParameters struct {

	// (String) Color of the template.
	// Color of the template.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Template data of the template.
	// Template data of the template.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Description of the template.
	// Description of the template.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Icon of the template.
	// Icon of the template.
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the template.
	// Name of the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// level template.
	// Identifier of the team. If not provided, creates a workspace-level template.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.Team
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v1.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v1.Selector `json:"teamIdSelector,omitempty" tf:"-"`

	// (String) Type of the template. Default issue.
	// Type of the template. **Default** `issue`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TemplateObservation struct {

	// (String) Color of the template.
	// Color of the template.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Template data of the template.
	// Template data of the template.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Description of the template.
	// Description of the template.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the template.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Icon of the template.
	// Icon of the template.
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the template.
	// Name of the template.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// level template.
	// Identifier of the team. If not provided, creates a workspace-level template.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// (String) Type of the template. Default issue.
	// Type of the template. **Default** `issue`.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type TemplateParameters struct {

	// (String) Color of the template.
	// Color of the template.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Template data of the template.
	// Template data of the template.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// (String) Description of the template.
	// Description of the template.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Icon of the template.
	// Icon of the template.
	// +kubebuilder:validation:Optional
	Icon *string `json:"icon,omitempty" tf:"icon,omitempty"`

	// (String) Name of the template.
	// Name of the template.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// level template.
	// Identifier of the team. If not provided, creates a workspace-level template.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.Team
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v1.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in linear to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v1.Selector `json:"teamIdSelector,omitempty" tf:"-"`

	// (String) Type of the template. Default issue.
	// Type of the template. **Default** `issue`.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// TemplateSpec defines the desired state of Template
type TemplateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     TemplateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TemplateInitParameters `json:"initProvider,omitempty"`
}

// TemplateStatus defines the observed state of Template.
type TemplateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TemplateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Template is the Schema for the Templates API. Linear template resource.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,linear}
type Template struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.data) || (has(self.initProvider) && has(self.initProvider.data))",message="spec.forProvider.data is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   TemplateSpec   `json:"spec"`
	Status TemplateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TemplateList contains a list of Templates
type TemplateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Template `json:"items"`
}

// Repository type metadata.
var (
	Template_Kind             = "Template"
	Template_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Template_Kind}.String()
	Template_KindAPIVersion   = Template_Kind + "." + CRDGroupVersion.String()
	Template_GroupVersionKind = CRDGroupVersion.WithKind(Template_Kind)
)

func init() {
	SchemeBuilder.Register(&Template{}, &TemplateList{})
}
