// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BranchInitParameters struct {

	// (Boolean) Whether the branch pattern is a regex. Default false.
	// Whether the branch pattern is a regex. **Default** `false`.
	IsRegex *bool `json:"isRegex,omitempty" tf:"is_regex,omitempty"`

	// (String) Branch pattern to match.
	// Branch pattern to match.
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`
}

type BranchObservation struct {

	// (String) Identifier of the team.
	// Identifier of the branch pattern.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Whether the branch pattern is a regex. Default false.
	// Whether the branch pattern is a regex. **Default** `false`.
	IsRegex *bool `json:"isRegex,omitempty" tf:"is_regex,omitempty"`

	// (String) Branch pattern to match.
	// Branch pattern to match.
	Pattern *string `json:"pattern,omitempty" tf:"pattern,omitempty"`
}

type BranchParameters struct {

	// (Boolean) Whether the branch pattern is a regex. Default false.
	// Whether the branch pattern is a regex. **Default** `false`.
	// +kubebuilder:validation:Optional
	IsRegex *bool `json:"isRegex,omitempty" tf:"is_regex,omitempty"`

	// (String) Branch pattern to match.
	// Branch pattern to match.
	// +kubebuilder:validation:Optional
	Pattern *string `json:"pattern" tf:"pattern,omitempty"`
}

type TeamWorkflowInitParameters struct {

	// (Attributes) Branch settings for this workflow state. (see below for nested schema)
	Branch *BranchInitParameters `json:"branch,omitempty" tf:"branch,omitempty"`

	// (String) Workflow state used when draft PRs are opened.
	// Workflow state used when draft PRs are opened.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	Draft *string `json:"draft,omitempty" tf:"draft,omitempty"`

	// Reference to a WorkflowState in linear to populate draft.
	// +kubebuilder:validation:Optional
	DraftRef *v1.NamespacedReference `json:"draftRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate draft.
	// +kubebuilder:validation:Optional
	DraftSelector *v1.NamespacedSelector `json:"draftSelector,omitempty" tf:"-"`

	// (String) Workflow state used when PRs are merged.
	// Workflow state used when PRs are merged.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	Merge *string `json:"merge,omitempty" tf:"merge,omitempty"`

	// Reference to a WorkflowState in linear to populate merge.
	// +kubebuilder:validation:Optional
	MergeRef *v1.NamespacedReference `json:"mergeRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate merge.
	// +kubebuilder:validation:Optional
	MergeSelector *v1.NamespacedSelector `json:"mergeSelector,omitempty" tf:"-"`

	// (String) Workflow state used when PRs become mergeable.
	// Workflow state used when PRs become mergeable.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	Mergeable *string `json:"mergeable,omitempty" tf:"mergeable,omitempty"`

	// Reference to a WorkflowState in linear to populate mergeable.
	// +kubebuilder:validation:Optional
	MergeableRef *v1.NamespacedReference `json:"mergeableRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate mergeable.
	// +kubebuilder:validation:Optional
	MergeableSelector *v1.NamespacedSelector `json:"mergeableSelector,omitempty" tf:"-"`

	// (String) Workflow state used when reviews are requested on PRs.
	// Workflow state used when reviews are requested on PRs.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	Review *string `json:"review,omitempty" tf:"review,omitempty"`

	// Reference to a WorkflowState in linear to populate review.
	// +kubebuilder:validation:Optional
	ReviewRef *v1.NamespacedReference `json:"reviewRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate review.
	// +kubebuilder:validation:Optional
	ReviewSelector *v1.NamespacedSelector `json:"reviewSelector,omitempty" tf:"-"`

	// (String) Workflow state used when PRs are opened.
	// Workflow state used when PRs are opened.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	Start *string `json:"start,omitempty" tf:"start,omitempty"`

	// Reference to a WorkflowState in linear to populate start.
	// +kubebuilder:validation:Optional
	StartRef *v1.NamespacedReference `json:"startRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate start.
	// +kubebuilder:validation:Optional
	StartSelector *v1.NamespacedSelector `json:"startSelector,omitempty" tf:"-"`
}

type TeamWorkflowObservation struct {

	// (Attributes) Branch settings for this workflow state. (see below for nested schema)
	Branch *BranchObservation `json:"branch,omitempty" tf:"branch,omitempty"`

	// (String) Workflow state used when draft PRs are opened.
	// Workflow state used when draft PRs are opened.
	Draft *string `json:"draft,omitempty" tf:"draft,omitempty"`

	// (String) Identifier of the team.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) Workflow state used when PRs are merged.
	// Workflow state used when PRs are merged.
	Merge *string `json:"merge,omitempty" tf:"merge,omitempty"`

	// (String) Workflow state used when PRs become mergeable.
	// Workflow state used when PRs become mergeable.
	Mergeable *string `json:"mergeable,omitempty" tf:"mergeable,omitempty"`

	// (String) Workflow state used when reviews are requested on PRs.
	// Workflow state used when reviews are requested on PRs.
	Review *string `json:"review,omitempty" tf:"review,omitempty"`

	// (String) Workflow state used when PRs are opened.
	// Workflow state used when PRs are opened.
	Start *string `json:"start,omitempty" tf:"start,omitempty"`
}

type TeamWorkflowParameters struct {

	// (Attributes) Branch settings for this workflow state. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Branch *BranchParameters `json:"branch,omitempty" tf:"branch,omitempty"`

	// (String) Workflow state used when draft PRs are opened.
	// Workflow state used when draft PRs are opened.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	Draft *string `json:"draft,omitempty" tf:"draft,omitempty"`

	// Reference to a WorkflowState in linear to populate draft.
	// +kubebuilder:validation:Optional
	DraftRef *v1.NamespacedReference `json:"draftRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate draft.
	// +kubebuilder:validation:Optional
	DraftSelector *v1.NamespacedSelector `json:"draftSelector,omitempty" tf:"-"`

	// (String) Workflow state used when PRs are merged.
	// Workflow state used when PRs are merged.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	Merge *string `json:"merge,omitempty" tf:"merge,omitempty"`

	// Reference to a WorkflowState in linear to populate merge.
	// +kubebuilder:validation:Optional
	MergeRef *v1.NamespacedReference `json:"mergeRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate merge.
	// +kubebuilder:validation:Optional
	MergeSelector *v1.NamespacedSelector `json:"mergeSelector,omitempty" tf:"-"`

	// (String) Workflow state used when PRs become mergeable.
	// Workflow state used when PRs become mergeable.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	Mergeable *string `json:"mergeable,omitempty" tf:"mergeable,omitempty"`

	// Reference to a WorkflowState in linear to populate mergeable.
	// +kubebuilder:validation:Optional
	MergeableRef *v1.NamespacedReference `json:"mergeableRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate mergeable.
	// +kubebuilder:validation:Optional
	MergeableSelector *v1.NamespacedSelector `json:"mergeableSelector,omitempty" tf:"-"`

	// (String) Workflow state used when reviews are requested on PRs.
	// Workflow state used when reviews are requested on PRs.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	Review *string `json:"review,omitempty" tf:"review,omitempty"`

	// Reference to a WorkflowState in linear to populate review.
	// +kubebuilder:validation:Optional
	ReviewRef *v1.NamespacedReference `json:"reviewRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate review.
	// +kubebuilder:validation:Optional
	ReviewSelector *v1.NamespacedSelector `json:"reviewSelector,omitempty" tf:"-"`

	// (String) Workflow state used when PRs are opened.
	// Workflow state used when PRs are opened.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/linear/v1alpha1.WorkflowState
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	Start *string `json:"start,omitempty" tf:"start,omitempty"`

	// Reference to a WorkflowState in linear to populate start.
	// +kubebuilder:validation:Optional
	StartRef *v1.NamespacedReference `json:"startRef,omitempty" tf:"-"`

	// Selector for a WorkflowState in linear to populate start.
	// +kubebuilder:validation:Optional
	StartSelector *v1.NamespacedSelector `json:"startSelector,omitempty" tf:"-"`
}

// TeamWorkflowSpec defines the desired state of TeamWorkflow
type TeamWorkflowSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            TeamWorkflowParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider TeamWorkflowInitParameters `json:"initProvider,omitempty"`
}

// TeamWorkflowStatus defines the observed state of TeamWorkflow.
type TeamWorkflowStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        TeamWorkflowObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// TeamWorkflow is the Schema for the TeamWorkflows API. Linear team workflow.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,linear}
type TeamWorkflow struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              TeamWorkflowSpec   `json:"spec"`
	Status            TeamWorkflowStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// TeamWorkflowList contains a list of TeamWorkflows
type TeamWorkflowList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []TeamWorkflow `json:"items"`
}

// Repository type metadata.
var (
	TeamWorkflow_Kind             = "TeamWorkflow"
	TeamWorkflow_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: TeamWorkflow_Kind}.String()
	TeamWorkflow_KindAPIVersion   = TeamWorkflow_Kind + "." + CRDGroupVersion.String()
	TeamWorkflow_GroupVersionKind = CRDGroupVersion.WithKind(TeamWorkflow_Kind)
)

func init() {
	SchemeBuilder.Register(&TeamWorkflow{}, &TeamWorkflowList{})
}
