// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type WorkspaceLabelInitParameters struct {

	// (String) Color of the label.
	// Color of the label.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the label.
	// Description of the label.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the label is a group (parent) label.
	// Whether the label is a group (parent) label.
	IsGroup *bool `json:"isGroup,omitempty" tf:"is_group,omitempty"`

	// (String) Parent (label group) of the label.
	// Parent (label group) of the label.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

type WorkspaceLabelObservation struct {

	// (String) Color of the label.
	// Color of the label.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the label.
	// Description of the label.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the label.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Boolean) Whether the label is a group (parent) label.
	// Whether the label is a group (parent) label.
	IsGroup *bool `json:"isGroup,omitempty" tf:"is_group,omitempty"`

	// (String) Parent (label group) of the label.
	// Parent (label group) of the label.
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

type WorkspaceLabelParameters struct {

	// (String) Color of the label.
	// Color of the label.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the label.
	// Description of the label.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the label is a group (parent) label.
	// Whether the label is a group (parent) label.
	// +kubebuilder:validation:Optional
	IsGroup *bool `json:"isGroup,omitempty" tf:"is_group,omitempty"`

	// (String) Parent (label group) of the label.
	// Parent (label group) of the label.
	// +kubebuilder:validation:Optional
	ParentID *string `json:"parentId,omitempty" tf:"parent_id,omitempty"`
}

// WorkspaceLabelSpec defines the desired state of WorkspaceLabel
type WorkspaceLabelSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            WorkspaceLabelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkspaceLabelInitParameters `json:"initProvider,omitempty"`
}

// WorkspaceLabelStatus defines the observed state of WorkspaceLabel.
type WorkspaceLabelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WorkspaceLabelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkspaceLabel is the Schema for the WorkspaceLabels API. Linear workspace label.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,linear}
type WorkspaceLabel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WorkspaceLabelSpec   `json:"spec"`
	Status            WorkspaceLabelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkspaceLabelList contains a list of WorkspaceLabels
type WorkspaceLabelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkspaceLabel `json:"items"`
}

// Repository type metadata.
var (
	WorkspaceLabel_Kind             = "WorkspaceLabel"
	WorkspaceLabel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkspaceLabel_Kind}.String()
	WorkspaceLabel_KindAPIVersion   = WorkspaceLabel_Kind + "." + CRDGroupVersion.String()
	WorkspaceLabel_GroupVersionKind = CRDGroupVersion.WithKind(WorkspaceLabel_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkspaceLabel{}, &WorkspaceLabelList{})
}
