//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BacklogWorkflowStateInitParameters) DeepCopyInto(out *BacklogWorkflowStateInitParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BacklogWorkflowStateInitParameters.
func (in *BacklogWorkflowStateInitParameters) DeepCopy() *BacklogWorkflowStateInitParameters {
	if in == nil {
		return nil
	}
	out := new(BacklogWorkflowStateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BacklogWorkflowStateObservation) DeepCopyInto(out *BacklogWorkflowStateObservation) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BacklogWorkflowStateObservation.
func (in *BacklogWorkflowStateObservation) DeepCopy() *BacklogWorkflowStateObservation {
	if in == nil {
		return nil
	}
	out := new(BacklogWorkflowStateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BacklogWorkflowStateParameters) DeepCopyInto(out *BacklogWorkflowStateParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BacklogWorkflowStateParameters.
func (in *BacklogWorkflowStateParameters) DeepCopy() *BacklogWorkflowStateParameters {
	if in == nil {
		return nil
	}
	out := new(BacklogWorkflowStateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanceledWorkflowStateInitParameters) DeepCopyInto(out *CanceledWorkflowStateInitParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanceledWorkflowStateInitParameters.
func (in *CanceledWorkflowStateInitParameters) DeepCopy() *CanceledWorkflowStateInitParameters {
	if in == nil {
		return nil
	}
	out := new(CanceledWorkflowStateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanceledWorkflowStateObservation) DeepCopyInto(out *CanceledWorkflowStateObservation) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanceledWorkflowStateObservation.
func (in *CanceledWorkflowStateObservation) DeepCopy() *CanceledWorkflowStateObservation {
	if in == nil {
		return nil
	}
	out := new(CanceledWorkflowStateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CanceledWorkflowStateParameters) DeepCopyInto(out *CanceledWorkflowStateParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CanceledWorkflowStateParameters.
func (in *CanceledWorkflowStateParameters) DeepCopy() *CanceledWorkflowStateParameters {
	if in == nil {
		return nil
	}
	out := new(CanceledWorkflowStateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletedWorkflowStateInitParameters) DeepCopyInto(out *CompletedWorkflowStateInitParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletedWorkflowStateInitParameters.
func (in *CompletedWorkflowStateInitParameters) DeepCopy() *CompletedWorkflowStateInitParameters {
	if in == nil {
		return nil
	}
	out := new(CompletedWorkflowStateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletedWorkflowStateObservation) DeepCopyInto(out *CompletedWorkflowStateObservation) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletedWorkflowStateObservation.
func (in *CompletedWorkflowStateObservation) DeepCopy() *CompletedWorkflowStateObservation {
	if in == nil {
		return nil
	}
	out := new(CompletedWorkflowStateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CompletedWorkflowStateParameters) DeepCopyInto(out *CompletedWorkflowStateParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CompletedWorkflowStateParameters.
func (in *CompletedWorkflowStateParameters) DeepCopy() *CompletedWorkflowStateParameters {
	if in == nil {
		return nil
	}
	out := new(CompletedWorkflowStateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyclesInitParameters) DeepCopyInto(out *CyclesInitParameters) {
	*out = *in
	if in.AutoAddCompleted != nil {
		in, out := &in.AutoAddCompleted, &out.AutoAddCompleted
		*out = new(bool)
		**out = **in
	}
	if in.AutoAddStarted != nil {
		in, out := &in.AutoAddStarted, &out.AutoAddStarted
		*out = new(bool)
		**out = **in
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(float64)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(float64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NeedForActive != nil {
		in, out := &in.NeedForActive, &out.NeedForActive
		*out = new(bool)
		**out = **in
	}
	if in.StartDay != nil {
		in, out := &in.StartDay, &out.StartDay
		*out = new(float64)
		**out = **in
	}
	if in.Upcoming != nil {
		in, out := &in.Upcoming, &out.Upcoming
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyclesInitParameters.
func (in *CyclesInitParameters) DeepCopy() *CyclesInitParameters {
	if in == nil {
		return nil
	}
	out := new(CyclesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyclesObservation) DeepCopyInto(out *CyclesObservation) {
	*out = *in
	if in.AutoAddCompleted != nil {
		in, out := &in.AutoAddCompleted, &out.AutoAddCompleted
		*out = new(bool)
		**out = **in
	}
	if in.AutoAddStarted != nil {
		in, out := &in.AutoAddStarted, &out.AutoAddStarted
		*out = new(bool)
		**out = **in
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(float64)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(float64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NeedForActive != nil {
		in, out := &in.NeedForActive, &out.NeedForActive
		*out = new(bool)
		**out = **in
	}
	if in.StartDay != nil {
		in, out := &in.StartDay, &out.StartDay
		*out = new(float64)
		**out = **in
	}
	if in.Upcoming != nil {
		in, out := &in.Upcoming, &out.Upcoming
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyclesObservation.
func (in *CyclesObservation) DeepCopy() *CyclesObservation {
	if in == nil {
		return nil
	}
	out := new(CyclesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CyclesParameters) DeepCopyInto(out *CyclesParameters) {
	*out = *in
	if in.AutoAddCompleted != nil {
		in, out := &in.AutoAddCompleted, &out.AutoAddCompleted
		*out = new(bool)
		**out = **in
	}
	if in.AutoAddStarted != nil {
		in, out := &in.AutoAddStarted, &out.AutoAddStarted
		*out = new(bool)
		**out = **in
	}
	if in.Cooldown != nil {
		in, out := &in.Cooldown, &out.Cooldown
		*out = new(float64)
		**out = **in
	}
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(float64)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.NeedForActive != nil {
		in, out := &in.NeedForActive, &out.NeedForActive
		*out = new(bool)
		**out = **in
	}
	if in.StartDay != nil {
		in, out := &in.StartDay, &out.StartDay
		*out = new(float64)
		**out = **in
	}
	if in.Upcoming != nil {
		in, out := &in.Upcoming, &out.Upcoming
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CyclesParameters.
func (in *CyclesParameters) DeepCopy() *CyclesParameters {
	if in == nil {
		return nil
	}
	out := new(CyclesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EstimationInitParameters) DeepCopyInto(out *EstimationInitParameters) {
	*out = *in
	if in.AllowZero != nil {
		in, out := &in.AllowZero, &out.AllowZero
		*out = new(bool)
		**out = **in
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(float64)
		**out = **in
	}
	if in.Extended != nil {
		in, out := &in.Extended, &out.Extended
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EstimationInitParameters.
func (in *EstimationInitParameters) DeepCopy() *EstimationInitParameters {
	if in == nil {
		return nil
	}
	out := new(EstimationInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EstimationObservation) DeepCopyInto(out *EstimationObservation) {
	*out = *in
	if in.AllowZero != nil {
		in, out := &in.AllowZero, &out.AllowZero
		*out = new(bool)
		**out = **in
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(float64)
		**out = **in
	}
	if in.Extended != nil {
		in, out := &in.Extended, &out.Extended
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EstimationObservation.
func (in *EstimationObservation) DeepCopy() *EstimationObservation {
	if in == nil {
		return nil
	}
	out := new(EstimationObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EstimationParameters) DeepCopyInto(out *EstimationParameters) {
	*out = *in
	if in.AllowZero != nil {
		in, out := &in.AllowZero, &out.AllowZero
		*out = new(bool)
		**out = **in
	}
	if in.Default != nil {
		in, out := &in.Default, &out.Default
		*out = new(float64)
		**out = **in
	}
	if in.Extended != nil {
		in, out := &in.Extended, &out.Extended
		*out = new(bool)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EstimationParameters.
func (in *EstimationParameters) DeepCopy() *EstimationParameters {
	if in == nil {
		return nil
	}
	out := new(EstimationParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartedWorkflowStateInitParameters) DeepCopyInto(out *StartedWorkflowStateInitParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartedWorkflowStateInitParameters.
func (in *StartedWorkflowStateInitParameters) DeepCopy() *StartedWorkflowStateInitParameters {
	if in == nil {
		return nil
	}
	out := new(StartedWorkflowStateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartedWorkflowStateObservation) DeepCopyInto(out *StartedWorkflowStateObservation) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartedWorkflowStateObservation.
func (in *StartedWorkflowStateObservation) DeepCopy() *StartedWorkflowStateObservation {
	if in == nil {
		return nil
	}
	out := new(StartedWorkflowStateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartedWorkflowStateParameters) DeepCopyInto(out *StartedWorkflowStateParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartedWorkflowStateParameters.
func (in *StartedWorkflowStateParameters) DeepCopy() *StartedWorkflowStateParameters {
	if in == nil {
		return nil
	}
	out := new(StartedWorkflowStateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Team) DeepCopyInto(out *Team) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Team.
func (in *Team) DeepCopy() *Team {
	if in == nil {
		return nil
	}
	out := new(Team)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Team) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamInitParameters) DeepCopyInto(out *TeamInitParameters) {
	*out = *in
	if in.AllowMembersToManageLabels != nil {
		in, out := &in.AllowMembersToManageLabels, &out.AllowMembersToManageLabels
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageMembers != nil {
		in, out := &in.AllowMembersToManageMembers, &out.AllowMembersToManageMembers
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageTeam != nil {
		in, out := &in.AllowMembersToManageTeam, &out.AllowMembersToManageTeam
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageTemplates != nil {
		in, out := &in.AllowMembersToManageTemplates, &out.AllowMembersToManageTemplates
		*out = new(bool)
		**out = **in
	}
	if in.AutoArchivePeriod != nil {
		in, out := &in.AutoArchivePeriod, &out.AutoArchivePeriod
		*out = new(float64)
		**out = **in
	}
	if in.AutoCloseChildIssues != nil {
		in, out := &in.AutoCloseChildIssues, &out.AutoCloseChildIssues
		*out = new(bool)
		**out = **in
	}
	if in.AutoCloseParentIssues != nil {
		in, out := &in.AutoCloseParentIssues, &out.AutoCloseParentIssues
		*out = new(bool)
		**out = **in
	}
	if in.AutoClosePeriod != nil {
		in, out := &in.AutoClosePeriod, &out.AutoClosePeriod
		*out = new(float64)
		**out = **in
	}
	if in.BacklogWorkflowState != nil {
		in, out := &in.BacklogWorkflowState, &out.BacklogWorkflowState
		*out = new(BacklogWorkflowStateInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.CanceledWorkflowState != nil {
		in, out := &in.CanceledWorkflowState, &out.CanceledWorkflowState
		*out = new(CanceledWorkflowStateInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.CompletedWorkflowState != nil {
		in, out := &in.CompletedWorkflowState, &out.CompletedWorkflowState
		*out = new(CompletedWorkflowStateInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Cycles != nil {
		in, out := &in.Cycles, &out.Cycles
		*out = new(CyclesInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnableIssueDefaultToBottom != nil {
		in, out := &in.EnableIssueDefaultToBottom, &out.EnableIssueDefaultToBottom
		*out = new(bool)
		**out = **in
	}
	if in.EnableIssueHistoryGrouping != nil {
		in, out := &in.EnableIssueHistoryGrouping, &out.EnableIssueHistoryGrouping
		*out = new(bool)
		**out = **in
	}
	if in.EnableThreadSummaries != nil {
		in, out := &in.EnableThreadSummaries, &out.EnableThreadSummaries
		*out = new(bool)
		**out = **in
	}
	if in.Estimation != nil {
		in, out := &in.Estimation, &out.Estimation
		*out = new(EstimationInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ParentID != nil {
		in, out := &in.ParentID, &out.ParentID
		*out = new(string)
		**out = **in
	}
	if in.Private != nil {
		in, out := &in.Private, &out.Private
		*out = new(bool)
		**out = **in
	}
	if in.StartedWorkflowState != nil {
		in, out := &in.StartedWorkflowState, &out.StartedWorkflowState
		*out = new(StartedWorkflowStateInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
	if in.Triage != nil {
		in, out := &in.Triage, &out.Triage
		*out = new(TriageInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.UnstartedWorkflowState != nil {
		in, out := &in.UnstartedWorkflowState, &out.UnstartedWorkflowState
		*out = new(UnstartedWorkflowStateInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamInitParameters.
func (in *TeamInitParameters) DeepCopy() *TeamInitParameters {
	if in == nil {
		return nil
	}
	out := new(TeamInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamList) DeepCopyInto(out *TeamList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Team, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamList.
func (in *TeamList) DeepCopy() *TeamList {
	if in == nil {
		return nil
	}
	out := new(TeamList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamObservation) DeepCopyInto(out *TeamObservation) {
	*out = *in
	if in.AllowMembersToManageLabels != nil {
		in, out := &in.AllowMembersToManageLabels, &out.AllowMembersToManageLabels
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageMembers != nil {
		in, out := &in.AllowMembersToManageMembers, &out.AllowMembersToManageMembers
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageTeam != nil {
		in, out := &in.AllowMembersToManageTeam, &out.AllowMembersToManageTeam
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageTemplates != nil {
		in, out := &in.AllowMembersToManageTemplates, &out.AllowMembersToManageTemplates
		*out = new(bool)
		**out = **in
	}
	if in.AutoArchivePeriod != nil {
		in, out := &in.AutoArchivePeriod, &out.AutoArchivePeriod
		*out = new(float64)
		**out = **in
	}
	if in.AutoCloseChildIssues != nil {
		in, out := &in.AutoCloseChildIssues, &out.AutoCloseChildIssues
		*out = new(bool)
		**out = **in
	}
	if in.AutoCloseParentIssues != nil {
		in, out := &in.AutoCloseParentIssues, &out.AutoCloseParentIssues
		*out = new(bool)
		**out = **in
	}
	if in.AutoClosePeriod != nil {
		in, out := &in.AutoClosePeriod, &out.AutoClosePeriod
		*out = new(float64)
		**out = **in
	}
	if in.BacklogWorkflowState != nil {
		in, out := &in.BacklogWorkflowState, &out.BacklogWorkflowState
		*out = new(BacklogWorkflowStateObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.CanceledWorkflowState != nil {
		in, out := &in.CanceledWorkflowState, &out.CanceledWorkflowState
		*out = new(CanceledWorkflowStateObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.CompletedWorkflowState != nil {
		in, out := &in.CompletedWorkflowState, &out.CompletedWorkflowState
		*out = new(CompletedWorkflowStateObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Cycles != nil {
		in, out := &in.Cycles, &out.Cycles
		*out = new(CyclesObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnableIssueDefaultToBottom != nil {
		in, out := &in.EnableIssueDefaultToBottom, &out.EnableIssueDefaultToBottom
		*out = new(bool)
		**out = **in
	}
	if in.EnableIssueHistoryGrouping != nil {
		in, out := &in.EnableIssueHistoryGrouping, &out.EnableIssueHistoryGrouping
		*out = new(bool)
		**out = **in
	}
	if in.EnableThreadSummaries != nil {
		in, out := &in.EnableThreadSummaries, &out.EnableThreadSummaries
		*out = new(bool)
		**out = **in
	}
	if in.Estimation != nil {
		in, out := &in.Estimation, &out.Estimation
		*out = new(EstimationObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ParentID != nil {
		in, out := &in.ParentID, &out.ParentID
		*out = new(string)
		**out = **in
	}
	if in.Private != nil {
		in, out := &in.Private, &out.Private
		*out = new(bool)
		**out = **in
	}
	if in.StartedWorkflowState != nil {
		in, out := &in.StartedWorkflowState, &out.StartedWorkflowState
		*out = new(StartedWorkflowStateObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
	if in.Triage != nil {
		in, out := &in.Triage, &out.Triage
		*out = new(TriageObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.UnstartedWorkflowState != nil {
		in, out := &in.UnstartedWorkflowState, &out.UnstartedWorkflowState
		*out = new(UnstartedWorkflowStateObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamObservation.
func (in *TeamObservation) DeepCopy() *TeamObservation {
	if in == nil {
		return nil
	}
	out := new(TeamObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamParameters) DeepCopyInto(out *TeamParameters) {
	*out = *in
	if in.AllowMembersToManageLabels != nil {
		in, out := &in.AllowMembersToManageLabels, &out.AllowMembersToManageLabels
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageMembers != nil {
		in, out := &in.AllowMembersToManageMembers, &out.AllowMembersToManageMembers
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageTeam != nil {
		in, out := &in.AllowMembersToManageTeam, &out.AllowMembersToManageTeam
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageTemplates != nil {
		in, out := &in.AllowMembersToManageTemplates, &out.AllowMembersToManageTemplates
		*out = new(bool)
		**out = **in
	}
	if in.AutoArchivePeriod != nil {
		in, out := &in.AutoArchivePeriod, &out.AutoArchivePeriod
		*out = new(float64)
		**out = **in
	}
	if in.AutoCloseChildIssues != nil {
		in, out := &in.AutoCloseChildIssues, &out.AutoCloseChildIssues
		*out = new(bool)
		**out = **in
	}
	if in.AutoCloseParentIssues != nil {
		in, out := &in.AutoCloseParentIssues, &out.AutoCloseParentIssues
		*out = new(bool)
		**out = **in
	}
	if in.AutoClosePeriod != nil {
		in, out := &in.AutoClosePeriod, &out.AutoClosePeriod
		*out = new(float64)
		**out = **in
	}
	if in.BacklogWorkflowState != nil {
		in, out := &in.BacklogWorkflowState, &out.BacklogWorkflowState
		*out = new(BacklogWorkflowStateParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.CanceledWorkflowState != nil {
		in, out := &in.CanceledWorkflowState, &out.CanceledWorkflowState
		*out = new(CanceledWorkflowStateParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.CompletedWorkflowState != nil {
		in, out := &in.CompletedWorkflowState, &out.CompletedWorkflowState
		*out = new(CompletedWorkflowStateParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Cycles != nil {
		in, out := &in.Cycles, &out.Cycles
		*out = new(CyclesParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.EnableIssueDefaultToBottom != nil {
		in, out := &in.EnableIssueDefaultToBottom, &out.EnableIssueDefaultToBottom
		*out = new(bool)
		**out = **in
	}
	if in.EnableIssueHistoryGrouping != nil {
		in, out := &in.EnableIssueHistoryGrouping, &out.EnableIssueHistoryGrouping
		*out = new(bool)
		**out = **in
	}
	if in.EnableThreadSummaries != nil {
		in, out := &in.EnableThreadSummaries, &out.EnableThreadSummaries
		*out = new(bool)
		**out = **in
	}
	if in.Estimation != nil {
		in, out := &in.Estimation, &out.Estimation
		*out = new(EstimationParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Icon != nil {
		in, out := &in.Icon, &out.Icon
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.ParentID != nil {
		in, out := &in.ParentID, &out.ParentID
		*out = new(string)
		**out = **in
	}
	if in.Private != nil {
		in, out := &in.Private, &out.Private
		*out = new(bool)
		**out = **in
	}
	if in.StartedWorkflowState != nil {
		in, out := &in.StartedWorkflowState, &out.StartedWorkflowState
		*out = new(StartedWorkflowStateParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Timezone != nil {
		in, out := &in.Timezone, &out.Timezone
		*out = new(string)
		**out = **in
	}
	if in.Triage != nil {
		in, out := &in.Triage, &out.Triage
		*out = new(TriageParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.UnstartedWorkflowState != nil {
		in, out := &in.UnstartedWorkflowState, &out.UnstartedWorkflowState
		*out = new(UnstartedWorkflowStateParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamParameters.
func (in *TeamParameters) DeepCopy() *TeamParameters {
	if in == nil {
		return nil
	}
	out := new(TeamParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamSpec) DeepCopyInto(out *TeamSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamSpec.
func (in *TeamSpec) DeepCopy() *TeamSpec {
	if in == nil {
		return nil
	}
	out := new(TeamSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamStatus) DeepCopyInto(out *TeamStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamStatus.
func (in *TeamStatus) DeepCopy() *TeamStatus {
	if in == nil {
		return nil
	}
	out := new(TeamStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriageInitParameters) DeepCopyInto(out *TriageInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RequirePriority != nil {
		in, out := &in.RequirePriority, &out.RequirePriority
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriageInitParameters.
func (in *TriageInitParameters) DeepCopy() *TriageInitParameters {
	if in == nil {
		return nil
	}
	out := new(TriageInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriageObservation) DeepCopyInto(out *TriageObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RequirePriority != nil {
		in, out := &in.RequirePriority, &out.RequirePriority
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriageObservation.
func (in *TriageObservation) DeepCopy() *TriageObservation {
	if in == nil {
		return nil
	}
	out := new(TriageObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TriageParameters) DeepCopyInto(out *TriageParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.RequirePriority != nil {
		in, out := &in.RequirePriority, &out.RequirePriority
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TriageParameters.
func (in *TriageParameters) DeepCopy() *TriageParameters {
	if in == nil {
		return nil
	}
	out := new(TriageParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstartedWorkflowStateInitParameters) DeepCopyInto(out *UnstartedWorkflowStateInitParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstartedWorkflowStateInitParameters.
func (in *UnstartedWorkflowStateInitParameters) DeepCopy() *UnstartedWorkflowStateInitParameters {
	if in == nil {
		return nil
	}
	out := new(UnstartedWorkflowStateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstartedWorkflowStateObservation) DeepCopyInto(out *UnstartedWorkflowStateObservation) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Position != nil {
		in, out := &in.Position, &out.Position
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstartedWorkflowStateObservation.
func (in *UnstartedWorkflowStateObservation) DeepCopy() *UnstartedWorkflowStateObservation {
	if in == nil {
		return nil
	}
	out := new(UnstartedWorkflowStateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *UnstartedWorkflowStateParameters) DeepCopyInto(out *UnstartedWorkflowStateParameters) {
	*out = *in
	if in.Color != nil {
		in, out := &in.Color, &out.Color
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new UnstartedWorkflowStateParameters.
func (in *UnstartedWorkflowStateParameters) DeepCopy() *UnstartedWorkflowStateParameters {
	if in == nil {
		return nil
	}
	out := new(UnstartedWorkflowStateParameters)
	in.DeepCopyInto(out)
	return out
}
