// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type WorkflowStateInitParameters struct {

	// (String) Color of the workflow state.
	// Color of the workflow state.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the workflow state.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) Position of the workflow state.
	// Position of the workflow state.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the team.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/team/v1alpha1.Team
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in team to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v1.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v1.Selector `json:"teamIdSelector,omitempty" tf:"-"`

	// (String) Type of the workflow state.
	// Type of the workflow state.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type WorkflowStateObservation struct {

	// (String) Color of the workflow state.
	// Color of the workflow state.
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the workflow state.
	// Description of the workflow state.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (String) Identifier of the workflow state.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Number) Position of the workflow state.
	// Position of the workflow state.
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the team.
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// (String) Type of the workflow state.
	// Type of the workflow state.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type WorkflowStateParameters struct {

	// (String) Color of the workflow state.
	// Color of the workflow state.
	// +kubebuilder:validation:Optional
	Color *string `json:"color,omitempty" tf:"color,omitempty"`

	// (String) Description of the workflow state.
	// Description of the workflow state.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Number) Position of the workflow state.
	// Position of the workflow state.
	// +kubebuilder:validation:Optional
	Position *float64 `json:"position,omitempty" tf:"position,omitempty"`

	// (String) Identifier of the team.
	// Identifier of the team.
	// +crossplane:generate:reference:type=github.com/avodah-inc/provider-linear/apis/team/v1alpha1.Team
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("id", true)
	// +kubebuilder:validation:Optional
	TeamID *string `json:"teamId,omitempty" tf:"team_id,omitempty"`

	// Reference to a Team in team to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDRef *v1.Reference `json:"teamIdRef,omitempty" tf:"-"`

	// Selector for a Team in team to populate teamId.
	// +kubebuilder:validation:Optional
	TeamIDSelector *v1.Selector `json:"teamIdSelector,omitempty" tf:"-"`

	// (String) Type of the workflow state.
	// Type of the workflow state.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// WorkflowStateSpec defines the desired state of WorkflowState
type WorkflowStateSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WorkflowStateParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkflowStateInitParameters `json:"initProvider,omitempty"`
}

// WorkflowStateStatus defines the observed state of WorkflowState.
type WorkflowStateStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WorkflowStateObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkflowState is the Schema for the WorkflowStates API. Linear team workflow state.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,linear}
type WorkflowState struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.color) || (has(self.initProvider) && has(self.initProvider.color))",message="spec.forProvider.color is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.position) || (has(self.initProvider) && has(self.initProvider.position))",message="spec.forProvider.position is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   WorkflowStateSpec   `json:"spec"`
	Status WorkflowStateStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkflowStateList contains a list of WorkflowStates
type WorkflowStateList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkflowState `json:"items"`
}

// Repository type metadata.
var (
	WorkflowState_Kind             = "WorkflowState"
	WorkflowState_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkflowState_Kind}.String()
	WorkflowState_KindAPIVersion   = WorkflowState_Kind + "." + CRDGroupVersion.String()
	WorkflowState_GroupVersionKind = CRDGroupVersion.WithKind(WorkflowState_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkflowState{}, &WorkflowStateList{})
}
