package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const listTemplate = `// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package %s

import resource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"

// GetItems of this %sList.
func (l *%sList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
`

const managedTemplate = `// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package %[1]s

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	resource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
)

// GetCondition of this %[2]s.
func (mg *%[2]s) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// SetConditions of this %[2]s.
func (mg *%[2]s) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// GetManagementPolicies of this %[2]s.
func (mg *%[2]s) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// SetManagementPolicies of this %[2]s.
func (mg *%[2]s) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// GetProviderConfigReference of this %[2]s.
func (mg *%[2]s) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

// SetProviderConfigReference of this %[2]s.
func (mg *%[2]s) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// GetWriteConnectionSecretToReference of this %[2]s.
func (mg *%[2]s) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetWriteConnectionSecretToReference of this %[2]s.
func (mg *%[2]s) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetDeletionPolicy of this %[2]s.
func (mg *%[2]s) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// SetDeletionPolicy of this %[2]s.
func (mg *%[2]s) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

var _ resource.Managed = &%[2]s{}
`

func runPostgen(root string) {
	// Patch webhook API in generated controllers.
	controllerDir := filepath.Join(root, "internal", "controller")
	re := regexp.MustCompile(`ctrl\.NewWebhookManagedBy\(mgr\)\.\s*\n\s*For\((&v1alpha1\.\w+\{\})\)\.\s*\n\s*Complete\(\)`)
	filepath.Walk(controllerDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || filepath.Base(path) != "zz_controller.go" {
			return nil
		}
		data, _ := os.ReadFile(path)
		if patched := re.ReplaceAllString(string(data), "ctrl.NewWebhookManagedBy(mgr, $1).Complete()"); patched != string(data) {
			os.WriteFile(path, []byte(patched), info.Mode())
			fmt.Printf("Patched webhook API: %s\n", path)
		}
		return nil
	})

	// Generate managed accessor and list shims for each API group.
	apisDir := filepath.Join(root, "apis")
	typeRe := regexp.MustCompile(`(?m)^type (\w+) struct \{$`)
	entries, _ := os.ReadDir(apisDir)
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		versionDir := filepath.Join(apisDir, entry.Name(), "v1alpha1")
		if _, err := os.Stat(versionDir); err != nil {
			continue
		}
		files, _ := filepath.Glob(filepath.Join(versionDir, "zz_*_types.go"))
		if len(files) == 0 {
			continue
		}
		data, _ := os.ReadFile(files[0])
		matches := typeRe.FindAllStringSubmatch(string(data), -1)
		var typeName string
		for _, m := range matches {
			n := m[1]
			if !strings.HasSuffix(n, "List") && !strings.HasSuffix(n, "Parameters") &&
				!strings.HasSuffix(n, "Observation") && !strings.HasSuffix(n, "Spec") &&
				!strings.HasSuffix(n, "Status") && !strings.HasSuffix(n, "InitParameters") {
				typeName = n
				break
			}
		}
		if typeName == "" {
			continue
		}
		os.WriteFile(filepath.Join(versionDir, "zz_generated_list.go"),
			[]byte(fmt.Sprintf(listTemplate, "v1alpha1", typeName, typeName)), 0644)
		os.WriteFile(filepath.Join(versionDir, "zz_generated_managed.go"),
			[]byte(fmt.Sprintf(managedTemplate, "v1alpha1", typeName)), 0644)
		fmt.Printf("Generated managed shims: %s\n", typeName)
	}
}
