package main

import (
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

const listTemplate = `// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package %s

import resource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"

// GetItems of this %sList.
func (l *%sList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
`

const managedTemplate = `// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package %[1]s

import (
	xpv1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	resource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
)

// GetCondition of this %[2]s.
func (mg *%[2]s) GetCondition(ct xpv1.ConditionType) xpv1.Condition {
	return mg.Status.GetCondition(ct)
}

// SetConditions of this %[2]s.
func (mg *%[2]s) SetConditions(c ...xpv1.Condition) {
	mg.Status.SetConditions(c...)
}

// GetManagementPolicies of this %[2]s.
func (mg *%[2]s) GetManagementPolicies() xpv1.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}

// SetManagementPolicies of this %[2]s.
func (mg *%[2]s) SetManagementPolicies(r xpv1.ManagementPolicies) {
	mg.Spec.ManagementPolicies = r
}

// GetProviderConfigReference of this %[2]s.
func (mg *%[2]s) GetProviderConfigReference() *xpv1.Reference {
	return mg.Spec.ProviderConfigReference
}

// SetProviderConfigReference of this %[2]s.
func (mg *%[2]s) SetProviderConfigReference(r *xpv1.Reference) {
	mg.Spec.ProviderConfigReference = r
}

// GetWriteConnectionSecretToReference of this %[2]s.
func (mg *%[2]s) GetWriteConnectionSecretToReference() *xpv1.SecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}

// SetWriteConnectionSecretToReference of this %[2]s.
func (mg *%[2]s) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}

// GetDeletionPolicy of this %[2]s.
func (mg *%[2]s) GetDeletionPolicy() xpv1.DeletionPolicy {
	return mg.Spec.DeletionPolicy
}

// SetDeletionPolicy of this %[2]s.
func (mg *%[2]s) SetDeletionPolicy(r xpv1.DeletionPolicy) {
	mg.Spec.DeletionPolicy = r
}

var _ resource.Managed = &%[2]s{}
`

func runPostgen(root string) {
	// Remove spurious per-resource-group directories generated by Upjet.
	// All resources use ShortGroup="" so they belong under apis/linear/v1alpha1
	// and internal/controller/linear/. Upjet also generates per-resource-name
	// group packages (e.g., apis/team/, internal/controller/team/) which are
	// duplicates that would produce incorrect CRD groups like team.linear.crossplane.io.
	cleanupSpuriousGroups(root)

	// Patch webhook API in generated controllers.
	controllerDir := filepath.Join(root, "internal", "controller")
	re := regexp.MustCompile(`ctrl\.NewWebhookManagedBy\(mgr\)\.\s*\n\s*For\((&v1alpha1\.\w+\{\})\)\.\s*\n\s*Complete\(\)`)
	filepath.Walk(controllerDir, func(path string, info os.FileInfo, err error) error {
		if err != nil || info.IsDir() || filepath.Base(path) != "zz_controller.go" {
			return nil
		}
		data, _ := os.ReadFile(path)
		if patched := re.ReplaceAllString(string(data), "ctrl.NewWebhookManagedBy(mgr, $1).Complete()"); patched != string(data) {
			os.WriteFile(path, []byte(patched), info.Mode())
			fmt.Printf("Patched webhook API: %s\n", path)
		}
		return nil
	})

	// Generate managed accessor and list shims for each API group.
	apisDir := filepath.Join(root, "apis")
	typeRe := regexp.MustCompile(`(?m)^type (\w+) struct \{$`)
	entries, _ := os.ReadDir(apisDir)
	for _, entry := range entries {
		if !entry.IsDir() {
			continue
		}
		versionDir := filepath.Join(apisDir, entry.Name(), "v1alpha1")
		if _, err := os.Stat(versionDir); err != nil {
			continue
		}
		files, _ := filepath.Glob(filepath.Join(versionDir, "zz_*_types.go"))
		if len(files) == 0 {
			continue
		}
		// Collect all root types from all types files in this directory.
		var typeNames []string
		for _, f := range files {
			data, _ := os.ReadFile(f)
			matches := typeRe.FindAllStringSubmatch(string(data), -1)
			for _, m := range matches {
				n := m[1]
				if !strings.HasSuffix(n, "List") && !strings.HasSuffix(n, "Parameters") &&
					!strings.HasSuffix(n, "Observation") && !strings.HasSuffix(n, "Spec") &&
					!strings.HasSuffix(n, "Status") && !strings.HasSuffix(n, "InitParameters") {
					typeNames = append(typeNames, n)
					break // one root type per file
				}
			}
		}
		// Generate a single list and managed file with all types.
		var listContent, managedContent string
		for _, typeName := range typeNames {
			listContent += fmt.Sprintf(`
// GetItems of this %[1]sList.
func (l *%[1]sList) GetItems() []resource.Managed {
	items := make([]resource.Managed, len(l.Items))
	for i := range l.Items {
		items[i] = &l.Items[i]
	}
	return items
}
`, typeName)
			managedContent += fmt.Sprintf(managedTemplate, "v1alpha1", typeName)
		}
		if len(typeNames) > 0 {
			header := "// SPDX-FileCopyrightText: 2026 Starlight Romero\n//\n// SPDX-License-Identifier: GPL-3.0-or-later\n\n// Code generated by upjet. DO NOT EDIT.\n\npackage v1alpha1\n\nimport resource \"github.com/crossplane/crossplane-runtime/v2/pkg/resource\"\n"
			os.WriteFile(filepath.Join(versionDir, "zz_generated_list.go"),
				[]byte(header+listContent), 0644)
			// For managed, each type gets its own block but they share the file.
			// The template already includes the package declaration, so we need a combined file.
			managedHeader := "// SPDX-FileCopyrightText: 2026 Starlight Romero\n//\n// SPDX-License-Identifier: GPL-3.0-or-later\n\n// Code generated by upjet. DO NOT EDIT.\n\npackage v1alpha1\n\nimport (\n\txpv1 \"github.com/crossplane/crossplane-runtime/v2/apis/common/v1\"\n\tresource \"github.com/crossplane/crossplane-runtime/v2/pkg/resource\"\n)\n"
			var managedBodies string
			for _, typeName := range typeNames {
				managedBodies += fmt.Sprintf(`
func (mg *%[1]s) GetCondition(ct xpv1.ConditionType) xpv1.Condition { return mg.Status.GetCondition(ct) }
func (mg *%[1]s) SetConditions(c ...xpv1.Condition) { mg.Status.SetConditions(c...) }
func (mg *%[1]s) GetManagementPolicies() xpv1.ManagementPolicies { return mg.Spec.ManagementPolicies }
func (mg *%[1]s) SetManagementPolicies(r xpv1.ManagementPolicies) { mg.Spec.ManagementPolicies = r }
func (mg *%[1]s) GetProviderConfigReference() *xpv1.Reference { return mg.Spec.ProviderConfigReference }
func (mg *%[1]s) SetProviderConfigReference(r *xpv1.Reference) { mg.Spec.ProviderConfigReference = r }
func (mg *%[1]s) GetWriteConnectionSecretToReference() *xpv1.SecretReference { return mg.Spec.WriteConnectionSecretToReference }
func (mg *%[1]s) SetWriteConnectionSecretToReference(r *xpv1.SecretReference) { mg.Spec.WriteConnectionSecretToReference = r }
func (mg *%[1]s) GetDeletionPolicy() xpv1.DeletionPolicy { return mg.Spec.DeletionPolicy }
func (mg *%[1]s) SetDeletionPolicy(r xpv1.DeletionPolicy) { mg.Spec.DeletionPolicy = r }
var _ resource.Managed = &%[1]s{}
`, typeName)
			}
			os.WriteFile(filepath.Join(versionDir, "zz_generated_managed.go"),
				[]byte(managedHeader+managedBodies), 0644)
			fmt.Printf("Generated managed shims: %v\n", typeNames)
		}
	}

	// Patch zz_setup.go to include custom (non-Upjet) controllers.
	setupFile := filepath.Join(controllerDir, "zz_setup.go")
	setupData, err := os.ReadFile(setupFile)
	if err == nil {
		setupContent := string(setupData)
		userImport := `user "github.com/avodah-inc/provider-linear/internal/controller/linear/user"`
		if !strings.Contains(setupContent, userImport) {
			// Add import in alphabetical order (before workflowstate).
			setupContent = strings.Replace(setupContent,
				`workflowstate "github.com/avodah-inc/provider-linear/internal/controller/linear/workflowstate"`,
				userImport+"\n\t"+`workflowstate "github.com/avodah-inc/provider-linear/internal/controller/linear/workflowstate"`, 1)
			// Add to Setup (after workspacesettings).
			setupContent = strings.Replace(setupContent,
				"workspacesettings.Setup,\n\t} {",
				"workspacesettings.Setup,\n\t\tuser.Setup,\n\t} {", 1)
			// Add to SetupGated (after workspacesettings).
			setupContent = strings.Replace(setupContent,
				"workspacesettings.SetupGated,\n\t} {",
				"workspacesettings.SetupGated,\n\t\tuser.SetupGated,\n\t} {", 1)
			os.WriteFile(setupFile, []byte(setupContent), 0755)
			fmt.Println("Patched zz_setup.go: added User controller")
		}
	}

	// Patch zz_register.go to include the ProviderConfig package.
	registerFile := filepath.Join(apisDir, "zz_register.go")
	data, err := os.ReadFile(registerFile)
	if err == nil {
		content := string(data)
		pcImport := `v1alpha1pc "github.com/avodah-inc/provider-linear/apis/v1alpha1"`
		if !strings.Contains(content, pcImport) {
			// Add import after the existing v1alpha1 import.
			content = strings.Replace(content,
				`v1alpha1 "github.com/avodah-inc/provider-linear/apis/linear/v1alpha1"`,
				`v1alpha1 "github.com/avodah-inc/provider-linear/apis/linear/v1alpha1"`+"\n\t"+pcImport, 1)
			// Add scheme registration.
			content = strings.Replace(content,
				"v1alpha1.SchemeBuilder.AddToScheme,",
				"v1alpha1.SchemeBuilder.AddToScheme,\n\t\tv1alpha1pc.SchemeBuilder.AddToScheme,", 1)
			os.WriteFile(registerFile, []byte(content), 0755)
			fmt.Println("Patched zz_register.go: added ProviderConfig package")
		}
	}
}

// cleanupSpuriousGroups removes per-resource-group directories that Upjet
// generates alongside the consolidated apis/linear/ and internal/controller/linear/
// packages. These would produce incorrect CRD API groups (e.g., team.linear.crossplane.io
// instead of linear.crossplane.io).
func cleanupSpuriousGroups(root string) {
	// Allowed top-level directories under apis/ (besides generate.go, zz_register.go)
	allowedAPIDirs := map[string]bool{"linear": true, "v1alpha1": true}
	apisDir := filepath.Join(root, "apis")
	entries, _ := os.ReadDir(apisDir)
	for _, e := range entries {
		if e.IsDir() && !allowedAPIDirs[e.Name()] {
			path := filepath.Join(apisDir, e.Name())
			os.RemoveAll(path)
			fmt.Printf("Removed spurious API group: %s\n", path)
		}
	}

	// Allowed top-level directories under internal/controller/
	allowedCtrlDirs := map[string]bool{"linear": true}
	ctrlDir := filepath.Join(root, "internal", "controller")
	entries, _ = os.ReadDir(ctrlDir)
	for _, e := range entries {
		if e.IsDir() && !allowedCtrlDirs[e.Name()] {
			path := filepath.Join(ctrlDir, e.Name())
			os.RemoveAll(path)
			fmt.Printf("Removed spurious controller group: %s\n", path)
		}
	}

	// Remove CRDs that don't belong to linear.crossplane.io
	crdsDir := filepath.Join(root, "package", "crds")
	crdFiles, _ := filepath.Glob(filepath.Join(crdsDir, "*.yaml"))
	for _, f := range crdFiles {
		base := filepath.Base(f)
		if !strings.HasPrefix(base, "linear.crossplane.io_") {
			os.Remove(f)
			fmt.Printf("Removed spurious CRD: %s\n", base)
		}
	}
}
