// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

// Package apis contains Kubernetes API for the provider.
package apis

import (
	"k8s.io/apimachinery/pkg/runtime"

	v1alpha1 "github.com/avodah-inc/provider-linear/apis/team/v1alpha1"
	v1alpha1teamlabel "github.com/avodah-inc/provider-linear/apis/teamlabel/v1alpha1"
	v1alpha1teamworkflow "github.com/avodah-inc/provider-linear/apis/teamworkflow/v1alpha1"
	v1alpha1template "github.com/avodah-inc/provider-linear/apis/template/v1alpha1"
	v1alpha1workflowstate "github.com/avodah-inc/provider-linear/apis/workflowstate/v1alpha1"
	v1alpha1workspacelabel "github.com/avodah-inc/provider-linear/apis/workspacelabel/v1alpha1"
	v1alpha1workspacesettings "github.com/avodah-inc/provider-linear/apis/workspacesettings/v1alpha1"
)

func init() {
	// Register the types with the Scheme so the components can map objects to GroupVersionKinds and back
	AddToSchemes = append(AddToSchemes,
		v1alpha1.SchemeBuilder.AddToScheme,
		v1alpha1teamlabel.SchemeBuilder.AddToScheme,
		v1alpha1teamworkflow.SchemeBuilder.AddToScheme,
		v1alpha1template.SchemeBuilder.AddToScheme,
		v1alpha1workflowstate.SchemeBuilder.AddToScheme,
		v1alpha1workspacelabel.SchemeBuilder.AddToScheme,
		v1alpha1workspacesettings.SchemeBuilder.AddToScheme,
	)
}

// AddToSchemes may be used to add all resources defined in the project to a Scheme
var AddToSchemes runtime.SchemeBuilder

// AddToScheme adds all Resources to the Scheme
func AddToScheme(s *runtime.Scheme) error {
	return AddToSchemes.AddToScheme(s)
}
