//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomersInitParameters) DeepCopyInto(out *CustomersInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomersInitParameters.
func (in *CustomersInitParameters) DeepCopy() *CustomersInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomersInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomersObservation) DeepCopyInto(out *CustomersObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomersObservation.
func (in *CustomersObservation) DeepCopy() *CustomersObservation {
	if in == nil {
		return nil
	}
	out := new(CustomersObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomersParameters) DeepCopyInto(out *CustomersParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomersParameters.
func (in *CustomersParameters) DeepCopy() *CustomersParameters {
	if in == nil {
		return nil
	}
	out := new(CustomersParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedInitParameters) DeepCopyInto(out *FeedInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedInitParameters.
func (in *FeedInitParameters) DeepCopy() *FeedInitParameters {
	if in == nil {
		return nil
	}
	out := new(FeedInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedObservation) DeepCopyInto(out *FeedObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedObservation.
func (in *FeedObservation) DeepCopy() *FeedObservation {
	if in == nil {
		return nil
	}
	out := new(FeedObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *FeedParameters) DeepCopyInto(out *FeedParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Schedule != nil {
		in, out := &in.Schedule, &out.Schedule
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new FeedParameters.
func (in *FeedParameters) DeepCopy() *FeedParameters {
	if in == nil {
		return nil
	}
	out := new(FeedParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitiativesInitParameters) DeepCopyInto(out *InitiativesInitParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.UpdateReminderDay != nil {
		in, out := &in.UpdateReminderDay, &out.UpdateReminderDay
		*out = new(string)
		**out = **in
	}
	if in.UpdateReminderFrequency != nil {
		in, out := &in.UpdateReminderFrequency, &out.UpdateReminderFrequency
		*out = new(float64)
		**out = **in
	}
	if in.UpdateReminderHour != nil {
		in, out := &in.UpdateReminderHour, &out.UpdateReminderHour
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitiativesInitParameters.
func (in *InitiativesInitParameters) DeepCopy() *InitiativesInitParameters {
	if in == nil {
		return nil
	}
	out := new(InitiativesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitiativesObservation) DeepCopyInto(out *InitiativesObservation) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.UpdateReminderDay != nil {
		in, out := &in.UpdateReminderDay, &out.UpdateReminderDay
		*out = new(string)
		**out = **in
	}
	if in.UpdateReminderFrequency != nil {
		in, out := &in.UpdateReminderFrequency, &out.UpdateReminderFrequency
		*out = new(float64)
		**out = **in
	}
	if in.UpdateReminderHour != nil {
		in, out := &in.UpdateReminderHour, &out.UpdateReminderHour
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitiativesObservation.
func (in *InitiativesObservation) DeepCopy() *InitiativesObservation {
	if in == nil {
		return nil
	}
	out := new(InitiativesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InitiativesParameters) DeepCopyInto(out *InitiativesParameters) {
	*out = *in
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.UpdateReminderDay != nil {
		in, out := &in.UpdateReminderDay, &out.UpdateReminderDay
		*out = new(string)
		**out = **in
	}
	if in.UpdateReminderFrequency != nil {
		in, out := &in.UpdateReminderFrequency, &out.UpdateReminderFrequency
		*out = new(float64)
		**out = **in
	}
	if in.UpdateReminderHour != nil {
		in, out := &in.UpdateReminderHour, &out.UpdateReminderHour
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InitiativesParameters.
func (in *InitiativesParameters) DeepCopy() *InitiativesParameters {
	if in == nil {
		return nil
	}
	out := new(InitiativesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectsInitParameters) DeepCopyInto(out *ProjectsInitParameters) {
	*out = *in
	if in.UpdateReminderDay != nil {
		in, out := &in.UpdateReminderDay, &out.UpdateReminderDay
		*out = new(string)
		**out = **in
	}
	if in.UpdateReminderFrequency != nil {
		in, out := &in.UpdateReminderFrequency, &out.UpdateReminderFrequency
		*out = new(float64)
		**out = **in
	}
	if in.UpdateReminderHour != nil {
		in, out := &in.UpdateReminderHour, &out.UpdateReminderHour
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectsInitParameters.
func (in *ProjectsInitParameters) DeepCopy() *ProjectsInitParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectsObservation) DeepCopyInto(out *ProjectsObservation) {
	*out = *in
	if in.UpdateReminderDay != nil {
		in, out := &in.UpdateReminderDay, &out.UpdateReminderDay
		*out = new(string)
		**out = **in
	}
	if in.UpdateReminderFrequency != nil {
		in, out := &in.UpdateReminderFrequency, &out.UpdateReminderFrequency
		*out = new(float64)
		**out = **in
	}
	if in.UpdateReminderHour != nil {
		in, out := &in.UpdateReminderHour, &out.UpdateReminderHour
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectsObservation.
func (in *ProjectsObservation) DeepCopy() *ProjectsObservation {
	if in == nil {
		return nil
	}
	out := new(ProjectsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ProjectsParameters) DeepCopyInto(out *ProjectsParameters) {
	*out = *in
	if in.UpdateReminderDay != nil {
		in, out := &in.UpdateReminderDay, &out.UpdateReminderDay
		*out = new(string)
		**out = **in
	}
	if in.UpdateReminderFrequency != nil {
		in, out := &in.UpdateReminderFrequency, &out.UpdateReminderFrequency
		*out = new(float64)
		**out = **in
	}
	if in.UpdateReminderHour != nil {
		in, out := &in.UpdateReminderHour, &out.UpdateReminderHour
		*out = new(float64)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ProjectsParameters.
func (in *ProjectsParameters) DeepCopy() *ProjectsParameters {
	if in == nil {
		return nil
	}
	out := new(ProjectsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSettings) DeepCopyInto(out *WorkspaceSettings) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSettings.
func (in *WorkspaceSettings) DeepCopy() *WorkspaceSettings {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSettings)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceSettings) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSettingsInitParameters) DeepCopyInto(out *WorkspaceSettingsInitParameters) {
	*out = *in
	if in.AllowMembersToCreateTeams != nil {
		in, out := &in.AllowMembersToCreateTeams, &out.AllowMembersToCreateTeams
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToInvite != nil {
		in, out := &in.AllowMembersToInvite, &out.AllowMembersToInvite
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageLabels != nil {
		in, out := &in.AllowMembersToManageLabels, &out.AllowMembersToManageLabels
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageTemplates != nil {
		in, out := &in.AllowMembersToManageTemplates, &out.AllowMembersToManageTemplates
		*out = new(bool)
		**out = **in
	}
	if in.Customers != nil {
		in, out := &in.Customers, &out.Customers
		*out = new(CustomersInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableGitLinkbackMessages != nil {
		in, out := &in.EnableGitLinkbackMessages, &out.EnableGitLinkbackMessages
		*out = new(bool)
		**out = **in
	}
	if in.EnableGitLinkbackMessagesPublic != nil {
		in, out := &in.EnableGitLinkbackMessagesPublic, &out.EnableGitLinkbackMessagesPublic
		*out = new(bool)
		**out = **in
	}
	if in.Feed != nil {
		in, out := &in.Feed, &out.Feed
		*out = new(FeedInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.FiscalYearStartMonth != nil {
		in, out := &in.FiscalYearStartMonth, &out.FiscalYearStartMonth
		*out = new(float64)
		**out = **in
	}
	if in.Initiatives != nil {
		in, out := &in.Initiatives, &out.Initiatives
		*out = new(InitiativesInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = new(ProjectsInitParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSettingsInitParameters.
func (in *WorkspaceSettingsInitParameters) DeepCopy() *WorkspaceSettingsInitParameters {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSettingsInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSettingsList) DeepCopyInto(out *WorkspaceSettingsList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]WorkspaceSettings, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSettingsList.
func (in *WorkspaceSettingsList) DeepCopy() *WorkspaceSettingsList {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSettingsList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *WorkspaceSettingsList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSettingsObservation) DeepCopyInto(out *WorkspaceSettingsObservation) {
	*out = *in
	if in.AllowMembersToCreateTeams != nil {
		in, out := &in.AllowMembersToCreateTeams, &out.AllowMembersToCreateTeams
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToInvite != nil {
		in, out := &in.AllowMembersToInvite, &out.AllowMembersToInvite
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageLabels != nil {
		in, out := &in.AllowMembersToManageLabels, &out.AllowMembersToManageLabels
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageTemplates != nil {
		in, out := &in.AllowMembersToManageTemplates, &out.AllowMembersToManageTemplates
		*out = new(bool)
		**out = **in
	}
	if in.Customers != nil {
		in, out := &in.Customers, &out.Customers
		*out = new(CustomersObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableGitLinkbackMessages != nil {
		in, out := &in.EnableGitLinkbackMessages, &out.EnableGitLinkbackMessages
		*out = new(bool)
		**out = **in
	}
	if in.EnableGitLinkbackMessagesPublic != nil {
		in, out := &in.EnableGitLinkbackMessagesPublic, &out.EnableGitLinkbackMessagesPublic
		*out = new(bool)
		**out = **in
	}
	if in.Feed != nil {
		in, out := &in.Feed, &out.Feed
		*out = new(FeedObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.FiscalYearStartMonth != nil {
		in, out := &in.FiscalYearStartMonth, &out.FiscalYearStartMonth
		*out = new(float64)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Initiatives != nil {
		in, out := &in.Initiatives, &out.Initiatives
		*out = new(InitiativesObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = new(ProjectsObservation)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSettingsObservation.
func (in *WorkspaceSettingsObservation) DeepCopy() *WorkspaceSettingsObservation {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSettingsObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSettingsParameters) DeepCopyInto(out *WorkspaceSettingsParameters) {
	*out = *in
	if in.AllowMembersToCreateTeams != nil {
		in, out := &in.AllowMembersToCreateTeams, &out.AllowMembersToCreateTeams
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToInvite != nil {
		in, out := &in.AllowMembersToInvite, &out.AllowMembersToInvite
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageLabels != nil {
		in, out := &in.AllowMembersToManageLabels, &out.AllowMembersToManageLabels
		*out = new(bool)
		**out = **in
	}
	if in.AllowMembersToManageTemplates != nil {
		in, out := &in.AllowMembersToManageTemplates, &out.AllowMembersToManageTemplates
		*out = new(bool)
		**out = **in
	}
	if in.Customers != nil {
		in, out := &in.Customers, &out.Customers
		*out = new(CustomersParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.EnableGitLinkbackMessages != nil {
		in, out := &in.EnableGitLinkbackMessages, &out.EnableGitLinkbackMessages
		*out = new(bool)
		**out = **in
	}
	if in.EnableGitLinkbackMessagesPublic != nil {
		in, out := &in.EnableGitLinkbackMessagesPublic, &out.EnableGitLinkbackMessagesPublic
		*out = new(bool)
		**out = **in
	}
	if in.Feed != nil {
		in, out := &in.Feed, &out.Feed
		*out = new(FeedParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.FiscalYearStartMonth != nil {
		in, out := &in.FiscalYearStartMonth, &out.FiscalYearStartMonth
		*out = new(float64)
		**out = **in
	}
	if in.Initiatives != nil {
		in, out := &in.Initiatives, &out.Initiatives
		*out = new(InitiativesParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Projects != nil {
		in, out := &in.Projects, &out.Projects
		*out = new(ProjectsParameters)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSettingsParameters.
func (in *WorkspaceSettingsParameters) DeepCopy() *WorkspaceSettingsParameters {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSettingsParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSettingsSpec) DeepCopyInto(out *WorkspaceSettingsSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSettingsSpec.
func (in *WorkspaceSettingsSpec) DeepCopy() *WorkspaceSettingsSpec {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSettingsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkspaceSettingsStatus) DeepCopyInto(out *WorkspaceSettingsStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkspaceSettingsStatus.
func (in *WorkspaceSettingsStatus) DeepCopy() *WorkspaceSettingsStatus {
	if in == nil {
		return nil
	}
	out := new(WorkspaceSettingsStatus)
	in.DeepCopyInto(out)
	return out
}
