// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CustomersInitParameters struct {

	// (Boolean) Enable customer requests. Default false.
	// Enable customer requests. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type CustomersObservation struct {

	// (Boolean) Enable customer requests. Default false.
	// Enable customer requests. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type CustomersParameters struct {

	// (Boolean) Enable customer requests. Default false.
	// Enable customer requests. **Default** `false`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`
}

type FeedInitParameters struct {

	// (Boolean) Enable customer requests. Default false.
	// Enable feed summaries for the workspace. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Schedule for feed summaries (daily, weekly). Default daily.
	// Schedule for feed summaries (daily, weekly). **Default** `daily`.
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type FeedObservation struct {

	// (Boolean) Enable customer requests. Default false.
	// Enable feed summaries for the workspace. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Schedule for feed summaries (daily, weekly). Default daily.
	// Schedule for feed summaries (daily, weekly). **Default** `daily`.
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type FeedParameters struct {

	// (Boolean) Enable customer requests. Default false.
	// Enable feed summaries for the workspace. **Default** `false`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Schedule for feed summaries (daily, weekly). Default daily.
	// Schedule for feed summaries (daily, weekly). **Default** `daily`.
	// +kubebuilder:validation:Optional
	Schedule *string `json:"schedule,omitempty" tf:"schedule,omitempty"`
}

type InitiativesInitParameters struct {

	// (Boolean) Enable customer requests. Default false.
	// Enable initiatives. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Day on which to prompt for initiative updates. Default Friday.
	// Day on which to prompt for initiative updates. **Default** `Friday`.
	UpdateReminderDay *string `json:"updateReminderDay,omitempty" tf:"update_reminder_day,omitempty"`

	// (Number) Frequency in weeks to send initiative update reminders. Default 0.
	// Frequency in weeks to send initiative update reminders. **Default** `0`.
	UpdateReminderFrequency *float64 `json:"updateReminderFrequency,omitempty" tf:"update_reminder_frequency,omitempty"`

	// 23) at which to prompt for initiative updates. Default 14.
	// Hour of day (0-23) at which to prompt for initiative updates. **Default** `14`.
	UpdateReminderHour *float64 `json:"updateReminderHour,omitempty" tf:"update_reminder_hour,omitempty"`
}

type InitiativesObservation struct {

	// (Boolean) Enable customer requests. Default false.
	// Enable initiatives. **Default** `false`.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Day on which to prompt for initiative updates. Default Friday.
	// Day on which to prompt for initiative updates. **Default** `Friday`.
	UpdateReminderDay *string `json:"updateReminderDay,omitempty" tf:"update_reminder_day,omitempty"`

	// (Number) Frequency in weeks to send initiative update reminders. Default 0.
	// Frequency in weeks to send initiative update reminders. **Default** `0`.
	UpdateReminderFrequency *float64 `json:"updateReminderFrequency,omitempty" tf:"update_reminder_frequency,omitempty"`

	// 23) at which to prompt for initiative updates. Default 14.
	// Hour of day (0-23) at which to prompt for initiative updates. **Default** `14`.
	UpdateReminderHour *float64 `json:"updateReminderHour,omitempty" tf:"update_reminder_hour,omitempty"`
}

type InitiativesParameters struct {

	// (Boolean) Enable customer requests. Default false.
	// Enable initiatives. **Default** `false`.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) Day on which to prompt for initiative updates. Default Friday.
	// Day on which to prompt for initiative updates. **Default** `Friday`.
	// +kubebuilder:validation:Optional
	UpdateReminderDay *string `json:"updateReminderDay,omitempty" tf:"update_reminder_day,omitempty"`

	// (Number) Frequency in weeks to send initiative update reminders. Default 0.
	// Frequency in weeks to send initiative update reminders. **Default** `0`.
	// +kubebuilder:validation:Optional
	UpdateReminderFrequency *float64 `json:"updateReminderFrequency,omitempty" tf:"update_reminder_frequency,omitempty"`

	// 23) at which to prompt for initiative updates. Default 14.
	// Hour of day (0-23) at which to prompt for initiative updates. **Default** `14`.
	// +kubebuilder:validation:Optional
	UpdateReminderHour *float64 `json:"updateReminderHour,omitempty" tf:"update_reminder_hour,omitempty"`
}

type ProjectsInitParameters struct {

	// (String) Day on which to prompt for initiative updates. Default Friday.
	// Day on which to prompt for project updates. **Default** `Friday`.
	UpdateReminderDay *string `json:"updateReminderDay,omitempty" tf:"update_reminder_day,omitempty"`

	// (Number) Frequency in weeks to send initiative update reminders. Default 0.
	// Frequency in weeks to send project update reminders. **Default** `0`.
	UpdateReminderFrequency *float64 `json:"updateReminderFrequency,omitempty" tf:"update_reminder_frequency,omitempty"`

	// 23) at which to prompt for initiative updates. Default 14.
	// Hour of day (0-23) at which to prompt for project updates. **Default** `14`.
	UpdateReminderHour *float64 `json:"updateReminderHour,omitempty" tf:"update_reminder_hour,omitempty"`
}

type ProjectsObservation struct {

	// (String) Day on which to prompt for initiative updates. Default Friday.
	// Day on which to prompt for project updates. **Default** `Friday`.
	UpdateReminderDay *string `json:"updateReminderDay,omitempty" tf:"update_reminder_day,omitempty"`

	// (Number) Frequency in weeks to send initiative update reminders. Default 0.
	// Frequency in weeks to send project update reminders. **Default** `0`.
	UpdateReminderFrequency *float64 `json:"updateReminderFrequency,omitempty" tf:"update_reminder_frequency,omitempty"`

	// 23) at which to prompt for initiative updates. Default 14.
	// Hour of day (0-23) at which to prompt for project updates. **Default** `14`.
	UpdateReminderHour *float64 `json:"updateReminderHour,omitempty" tf:"update_reminder_hour,omitempty"`
}

type ProjectsParameters struct {

	// (String) Day on which to prompt for initiative updates. Default Friday.
	// Day on which to prompt for project updates. **Default** `Friday`.
	// +kubebuilder:validation:Optional
	UpdateReminderDay *string `json:"updateReminderDay,omitempty" tf:"update_reminder_day,omitempty"`

	// (Number) Frequency in weeks to send initiative update reminders. Default 0.
	// Frequency in weeks to send project update reminders. **Default** `0`.
	// +kubebuilder:validation:Optional
	UpdateReminderFrequency *float64 `json:"updateReminderFrequency,omitempty" tf:"update_reminder_frequency,omitempty"`

	// 23) at which to prompt for initiative updates. Default 14.
	// Hour of day (0-23) at which to prompt for project updates. **Default** `14`.
	// +kubebuilder:validation:Optional
	UpdateReminderHour *float64 `json:"updateReminderHour,omitempty" tf:"update_reminder_hour,omitempty"`
}

type WorkspaceSettingsInitParameters struct {

	// (Boolean) Allow members to create new teams in the workspace. Default true.
	// Allow members to create new teams in the workspace. **Default** `true`.
	AllowMembersToCreateTeams *bool `json:"allowMembersToCreateTeams,omitempty" tf:"allow_members_to_create_teams,omitempty"`

	// (Boolean) Allow members to invite new members to the workspace. Default true.
	// Allow members to invite new members to the workspace. **Default** `true`.
	AllowMembersToInvite *bool `json:"allowMembersToInvite,omitempty" tf:"allow_members_to_invite,omitempty"`

	// (Boolean) Allow members to manage labels in the workspace. Default true.
	// Allow members to manage labels in the workspace. **Default** `true`.
	AllowMembersToManageLabels *bool `json:"allowMembersToManageLabels,omitempty" tf:"allow_members_to_manage_labels,omitempty"`

	// (Boolean) Allow members to manage templates in the workspace. Default true.
	// Allow members to manage templates in the workspace. **Default** `true`.
	AllowMembersToManageTemplates *bool `json:"allowMembersToManageTemplates,omitempty" tf:"allow_members_to_manage_templates,omitempty"`

	// (Attributes) Customer Requests settings for the workspace. (see below for nested schema)
	Customers *CustomersInitParameters `json:"customers,omitempty" tf:"customers,omitempty"`

	// (Boolean) Enable git linkbacks for private repositories. Default true.
	// Enable git linkbacks for private repositories. **Default** `true`.
	EnableGitLinkbackMessages *bool `json:"enableGitLinkbackMessages,omitempty" tf:"enable_git_linkback_messages,omitempty"`

	// (Boolean) Enable git linkbacks for public repositories. Default false.
	// Enable git linkbacks for public repositories. **Default** `false`.
	EnableGitLinkbackMessagesPublic *bool `json:"enableGitLinkbackMessagesPublic,omitempty" tf:"enable_git_linkback_messages_public,omitempty"`

	// (Attributes) Feed settings for the workspace. (see below for nested schema)
	Feed *FeedInitParameters `json:"feed,omitempty" tf:"feed,omitempty"`

	// (Number) Month at which the fiscal year starts. Default 0 representing January.
	// Month at which the fiscal year starts. **Default** `0` representing January.
	FiscalYearStartMonth *float64 `json:"fiscalYearStartMonth,omitempty" tf:"fiscal_year_start_month,omitempty"`

	// (Attributes) Initiative settings for the workspace. (see below for nested schema)
	Initiatives *InitiativesInitParameters `json:"initiatives,omitempty" tf:"initiatives,omitempty"`

	// (Attributes) Project settings for the workspace. (see below for nested schema)
	Projects *ProjectsInitParameters `json:"projects,omitempty" tf:"projects,omitempty"`
}

type WorkspaceSettingsObservation struct {

	// (Boolean) Allow members to create new teams in the workspace. Default true.
	// Allow members to create new teams in the workspace. **Default** `true`.
	AllowMembersToCreateTeams *bool `json:"allowMembersToCreateTeams,omitempty" tf:"allow_members_to_create_teams,omitempty"`

	// (Boolean) Allow members to invite new members to the workspace. Default true.
	// Allow members to invite new members to the workspace. **Default** `true`.
	AllowMembersToInvite *bool `json:"allowMembersToInvite,omitempty" tf:"allow_members_to_invite,omitempty"`

	// (Boolean) Allow members to manage labels in the workspace. Default true.
	// Allow members to manage labels in the workspace. **Default** `true`.
	AllowMembersToManageLabels *bool `json:"allowMembersToManageLabels,omitempty" tf:"allow_members_to_manage_labels,omitempty"`

	// (Boolean) Allow members to manage templates in the workspace. Default true.
	// Allow members to manage templates in the workspace. **Default** `true`.
	AllowMembersToManageTemplates *bool `json:"allowMembersToManageTemplates,omitempty" tf:"allow_members_to_manage_templates,omitempty"`

	// (Attributes) Customer Requests settings for the workspace. (see below for nested schema)
	Customers *CustomersObservation `json:"customers,omitempty" tf:"customers,omitempty"`

	// (Boolean) Enable git linkbacks for private repositories. Default true.
	// Enable git linkbacks for private repositories. **Default** `true`.
	EnableGitLinkbackMessages *bool `json:"enableGitLinkbackMessages,omitempty" tf:"enable_git_linkback_messages,omitempty"`

	// (Boolean) Enable git linkbacks for public repositories. Default false.
	// Enable git linkbacks for public repositories. **Default** `false`.
	EnableGitLinkbackMessagesPublic *bool `json:"enableGitLinkbackMessagesPublic,omitempty" tf:"enable_git_linkback_messages_public,omitempty"`

	// (Attributes) Feed settings for the workspace. (see below for nested schema)
	Feed *FeedObservation `json:"feed,omitempty" tf:"feed,omitempty"`

	// (Number) Month at which the fiscal year starts. Default 0 representing January.
	// Month at which the fiscal year starts. **Default** `0` representing January.
	FiscalYearStartMonth *float64 `json:"fiscalYearStartMonth,omitempty" tf:"fiscal_year_start_month,omitempty"`

	// (String) Identifier of the workspace.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Attributes) Initiative settings for the workspace. (see below for nested schema)
	Initiatives *InitiativesObservation `json:"initiatives,omitempty" tf:"initiatives,omitempty"`

	// (Attributes) Project settings for the workspace. (see below for nested schema)
	Projects *ProjectsObservation `json:"projects,omitempty" tf:"projects,omitempty"`
}

type WorkspaceSettingsParameters struct {

	// (Boolean) Allow members to create new teams in the workspace. Default true.
	// Allow members to create new teams in the workspace. **Default** `true`.
	// +kubebuilder:validation:Optional
	AllowMembersToCreateTeams *bool `json:"allowMembersToCreateTeams,omitempty" tf:"allow_members_to_create_teams,omitempty"`

	// (Boolean) Allow members to invite new members to the workspace. Default true.
	// Allow members to invite new members to the workspace. **Default** `true`.
	// +kubebuilder:validation:Optional
	AllowMembersToInvite *bool `json:"allowMembersToInvite,omitempty" tf:"allow_members_to_invite,omitempty"`

	// (Boolean) Allow members to manage labels in the workspace. Default true.
	// Allow members to manage labels in the workspace. **Default** `true`.
	// +kubebuilder:validation:Optional
	AllowMembersToManageLabels *bool `json:"allowMembersToManageLabels,omitempty" tf:"allow_members_to_manage_labels,omitempty"`

	// (Boolean) Allow members to manage templates in the workspace. Default true.
	// Allow members to manage templates in the workspace. **Default** `true`.
	// +kubebuilder:validation:Optional
	AllowMembersToManageTemplates *bool `json:"allowMembersToManageTemplates,omitempty" tf:"allow_members_to_manage_templates,omitempty"`

	// (Attributes) Customer Requests settings for the workspace. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Customers *CustomersParameters `json:"customers,omitempty" tf:"customers,omitempty"`

	// (Boolean) Enable git linkbacks for private repositories. Default true.
	// Enable git linkbacks for private repositories. **Default** `true`.
	// +kubebuilder:validation:Optional
	EnableGitLinkbackMessages *bool `json:"enableGitLinkbackMessages,omitempty" tf:"enable_git_linkback_messages,omitempty"`

	// (Boolean) Enable git linkbacks for public repositories. Default false.
	// Enable git linkbacks for public repositories. **Default** `false`.
	// +kubebuilder:validation:Optional
	EnableGitLinkbackMessagesPublic *bool `json:"enableGitLinkbackMessagesPublic,omitempty" tf:"enable_git_linkback_messages_public,omitempty"`

	// (Attributes) Feed settings for the workspace. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Feed *FeedParameters `json:"feed,omitempty" tf:"feed,omitempty"`

	// (Number) Month at which the fiscal year starts. Default 0 representing January.
	// Month at which the fiscal year starts. **Default** `0` representing January.
	// +kubebuilder:validation:Optional
	FiscalYearStartMonth *float64 `json:"fiscalYearStartMonth,omitempty" tf:"fiscal_year_start_month,omitempty"`

	// (Attributes) Initiative settings for the workspace. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Initiatives *InitiativesParameters `json:"initiatives,omitempty" tf:"initiatives,omitempty"`

	// (Attributes) Project settings for the workspace. (see below for nested schema)
	// +kubebuilder:validation:Optional
	Projects *ProjectsParameters `json:"projects,omitempty" tf:"projects,omitempty"`
}

// WorkspaceSettingsSpec defines the desired state of WorkspaceSettings
type WorkspaceSettingsSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     WorkspaceSettingsParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider WorkspaceSettingsInitParameters `json:"initProvider,omitempty"`
}

// WorkspaceSettingsStatus defines the observed state of WorkspaceSettings.
type WorkspaceSettingsStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        WorkspaceSettingsObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// WorkspaceSettings is the Schema for the WorkspaceSettingss API. Linear workspace settings.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,linear}
type WorkspaceSettings struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              WorkspaceSettingsSpec   `json:"spec"`
	Status            WorkspaceSettingsStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// WorkspaceSettingsList contains a list of WorkspaceSettingss
type WorkspaceSettingsList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []WorkspaceSettings `json:"items"`
}

// Repository type metadata.
var (
	WorkspaceSettings_Kind             = "WorkspaceSettings"
	WorkspaceSettings_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: WorkspaceSettings_Kind}.String()
	WorkspaceSettings_KindAPIVersion   = WorkspaceSettings_Kind + "." + CRDGroupVersion.String()
	WorkspaceSettings_GroupVersionKind = CRDGroupVersion.WithKind(WorkspaceSettings_Kind)
)

func init() {
	SchemeBuilder.Register(&WorkspaceSettings{}, &WorkspaceSettingsList{})
}
