//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 Starlight Romero
//
// SPDX-License-Identifier: GPL-3.0-or-later

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchInitParameters) DeepCopyInto(out *BranchInitParameters) {
	*out = *in
	if in.IsRegex != nil {
		in, out := &in.IsRegex, &out.IsRegex
		*out = new(bool)
		**out = **in
	}
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchInitParameters.
func (in *BranchInitParameters) DeepCopy() *BranchInitParameters {
	if in == nil {
		return nil
	}
	out := new(BranchInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchObservation) DeepCopyInto(out *BranchObservation) {
	*out = *in
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IsRegex != nil {
		in, out := &in.IsRegex, &out.IsRegex
		*out = new(bool)
		**out = **in
	}
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchObservation.
func (in *BranchObservation) DeepCopy() *BranchObservation {
	if in == nil {
		return nil
	}
	out := new(BranchObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BranchParameters) DeepCopyInto(out *BranchParameters) {
	*out = *in
	if in.IsRegex != nil {
		in, out := &in.IsRegex, &out.IsRegex
		*out = new(bool)
		**out = **in
	}
	if in.Pattern != nil {
		in, out := &in.Pattern, &out.Pattern
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BranchParameters.
func (in *BranchParameters) DeepCopy() *BranchParameters {
	if in == nil {
		return nil
	}
	out := new(BranchParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamWorkflow) DeepCopyInto(out *TeamWorkflow) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamWorkflow.
func (in *TeamWorkflow) DeepCopy() *TeamWorkflow {
	if in == nil {
		return nil
	}
	out := new(TeamWorkflow)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamWorkflow) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamWorkflowInitParameters) DeepCopyInto(out *TeamWorkflowInitParameters) {
	*out = *in
	if in.Branch != nil {
		in, out := &in.Branch, &out.Branch
		*out = new(BranchInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Draft != nil {
		in, out := &in.Draft, &out.Draft
		*out = new(string)
		**out = **in
	}
	if in.DraftRef != nil {
		in, out := &in.DraftRef, &out.DraftRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.DraftSelector != nil {
		in, out := &in.DraftSelector, &out.DraftSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Merge != nil {
		in, out := &in.Merge, &out.Merge
		*out = new(string)
		**out = **in
	}
	if in.MergeRef != nil {
		in, out := &in.MergeRef, &out.MergeRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.MergeSelector != nil {
		in, out := &in.MergeSelector, &out.MergeSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Mergeable != nil {
		in, out := &in.Mergeable, &out.Mergeable
		*out = new(string)
		**out = **in
	}
	if in.MergeableRef != nil {
		in, out := &in.MergeableRef, &out.MergeableRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.MergeableSelector != nil {
		in, out := &in.MergeableSelector, &out.MergeableSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Review != nil {
		in, out := &in.Review, &out.Review
		*out = new(string)
		**out = **in
	}
	if in.ReviewRef != nil {
		in, out := &in.ReviewRef, &out.ReviewRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ReviewSelector != nil {
		in, out := &in.ReviewSelector, &out.ReviewSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.StartRef != nil {
		in, out := &in.StartRef, &out.StartRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.StartSelector != nil {
		in, out := &in.StartSelector, &out.StartSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamWorkflowInitParameters.
func (in *TeamWorkflowInitParameters) DeepCopy() *TeamWorkflowInitParameters {
	if in == nil {
		return nil
	}
	out := new(TeamWorkflowInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamWorkflowList) DeepCopyInto(out *TeamWorkflowList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TeamWorkflow, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamWorkflowList.
func (in *TeamWorkflowList) DeepCopy() *TeamWorkflowList {
	if in == nil {
		return nil
	}
	out := new(TeamWorkflowList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *TeamWorkflowList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamWorkflowObservation) DeepCopyInto(out *TeamWorkflowObservation) {
	*out = *in
	if in.Branch != nil {
		in, out := &in.Branch, &out.Branch
		*out = new(BranchObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.Draft != nil {
		in, out := &in.Draft, &out.Draft
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Merge != nil {
		in, out := &in.Merge, &out.Merge
		*out = new(string)
		**out = **in
	}
	if in.Mergeable != nil {
		in, out := &in.Mergeable, &out.Mergeable
		*out = new(string)
		**out = **in
	}
	if in.Review != nil {
		in, out := &in.Review, &out.Review
		*out = new(string)
		**out = **in
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamWorkflowObservation.
func (in *TeamWorkflowObservation) DeepCopy() *TeamWorkflowObservation {
	if in == nil {
		return nil
	}
	out := new(TeamWorkflowObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamWorkflowParameters) DeepCopyInto(out *TeamWorkflowParameters) {
	*out = *in
	if in.Branch != nil {
		in, out := &in.Branch, &out.Branch
		*out = new(BranchParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.Draft != nil {
		in, out := &in.Draft, &out.Draft
		*out = new(string)
		**out = **in
	}
	if in.DraftRef != nil {
		in, out := &in.DraftRef, &out.DraftRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.DraftSelector != nil {
		in, out := &in.DraftSelector, &out.DraftSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Merge != nil {
		in, out := &in.Merge, &out.Merge
		*out = new(string)
		**out = **in
	}
	if in.MergeRef != nil {
		in, out := &in.MergeRef, &out.MergeRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.MergeSelector != nil {
		in, out := &in.MergeSelector, &out.MergeSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Mergeable != nil {
		in, out := &in.Mergeable, &out.Mergeable
		*out = new(string)
		**out = **in
	}
	if in.MergeableRef != nil {
		in, out := &in.MergeableRef, &out.MergeableRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.MergeableSelector != nil {
		in, out := &in.MergeableSelector, &out.MergeableSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Review != nil {
		in, out := &in.Review, &out.Review
		*out = new(string)
		**out = **in
	}
	if in.ReviewRef != nil {
		in, out := &in.ReviewRef, &out.ReviewRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ReviewSelector != nil {
		in, out := &in.ReviewSelector, &out.ReviewSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Start != nil {
		in, out := &in.Start, &out.Start
		*out = new(string)
		**out = **in
	}
	if in.StartRef != nil {
		in, out := &in.StartRef, &out.StartRef
		*out = new(v1.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.StartSelector != nil {
		in, out := &in.StartSelector, &out.StartSelector
		*out = new(v1.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamWorkflowParameters.
func (in *TeamWorkflowParameters) DeepCopy() *TeamWorkflowParameters {
	if in == nil {
		return nil
	}
	out := new(TeamWorkflowParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamWorkflowSpec) DeepCopyInto(out *TeamWorkflowSpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamWorkflowSpec.
func (in *TeamWorkflowSpec) DeepCopy() *TeamWorkflowSpec {
	if in == nil {
		return nil
	}
	out := new(TeamWorkflowSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TeamWorkflowStatus) DeepCopyInto(out *TeamWorkflowStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TeamWorkflowStatus.
func (in *TeamWorkflowStatus) DeepCopy() *TeamWorkflowStatus {
	if in == nil {
		return nil
	}
	out := new(TeamWorkflowStatus)
	in.DeepCopyInto(out)
	return out
}
